//! Drift gate for the workflow definition / node manifest schema contracts.
//!
//! `schemas/runtime-v1/WorkflowDefinition.schema.json` and
//! `NodeManifestVersion.schema.json` are generated by the `generate-contracts`
//! bin. These tests fail when the committed artifacts drift from the current
//! Rust types, so the JSON contract can never silently lag behind the code
//! (the schemaVersion enum previously drifted two major versions behind).

use std::fs;

use schemars::schema_for;
use serde_json::Value;

#[test]
fn workflow_definition_schema_does_not_drift() {
    let committed = read_committed("WorkflowDefinition");
    let generated = serde_json::to_value(schema_for!(agentx_domain::WorkflowDefinition))
        .expect("WorkflowDefinition schema is serializable");
    assert_eq!(
        committed, generated,
        "schema drift for WorkflowDefinition: re-run `cargo run -p agentx-runtime-contracts --bin generate-contracts -- schemas/runtime-v1 openapi/runtime-internal-v1.json openapi/observability-internal-v1.json`"
    );
    assert_eq!(
        committed["$defs"]["WorkflowSchemaVersion"]["enum"][0],
        agentx_domain::WORKFLOW_SCHEMA_VERSION,
        "WorkflowDefinition schema enum must track the current schema version"
    );
}

#[test]
fn node_manifest_schema_does_not_drift() {
    let committed = read_committed("NodeManifestVersion");
    let generated = serde_json::to_value(schema_for!(agentx_node_protocol::NodeManifestVersion))
        .expect("NodeManifestVersion schema is serializable");
    assert_eq!(
        committed, generated,
        "schema drift for NodeManifestVersion: re-run the generate-contracts bin"
    );
    assert_eq!(
        committed["$defs"]["NodeProtocolVersion"]["enum"][0], "2.0",
        "NodeManifestVersion protocol enum must stay pinned"
    );
}

fn read_committed(name: &str) -> Value {
    let file = fs::read_to_string(format!(
        "{}/../../schemas/runtime-v1/{name}.schema.json",
        env!("CARGO_MANIFEST_DIR")
    ))
    .unwrap_or_else(|error| panic!("failed to read generated schema {name}: {error}"));
    serde_json::from_str(&file).expect("generated schema is valid JSON")
}
