-- Generated by scripts/generate-v2-initial-schema.ps1.
-- V2-01 uses empty databases: do not append the V1 migration chain here.
-- Cross-plane relations are logical references and therefore have no FKs.
SET NAMES utf8mb4;
SET time_zone = '+00:00';
CREATE TABLE agent_iterations (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    agent_run_id BINARY(16) NOT NULL,
    iteration_index INT UNSIGNED NOT NULL,
    status ENUM('running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'running',
    state_before_hash CHAR(64) NOT NULL,
    state_after_hash CHAR(64) NULL,
    state_artifact_id BINARY(16) NULL,
    stop_reason VARCHAR(64) NULL,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agent_iteration (agent_run_id, iteration_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    status ENUM('running', 'succeeded', 'failed', 'cancelled') NOT NULL DEFAULT 'running',
    budget_json JSON NOT NULL,
    iteration_count INT UNSIGNED NOT NULL DEFAULT 0,
    model_call_count INT UNSIGNED NOT NULL DEFAULT 0,
    tool_call_count INT UNSIGNED NOT NULL DEFAULT 0,
    reserved_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reserved_cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    state_artifact_id BINARY(16) NULL,
    state_hash CHAR(64) NULL,
    stop_reason VARCHAR(64) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_agent_run_node (tenant_id, node_execution_id),
    KEY idx_agent_run_execution (tenant_id, execution_id, started_at),
    KEY idx_agent_run_attempt (tenant_id, attempt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Durable Agent Core session state (P3-05).  Entries are append-only; the
-- Register is the only mutable recovery authority.  There is intentionally
-- no compatibility table or migration for the removed monolithic state.
CREATE TABLE agent_session_entries (
    entry_id VARCHAR(191) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    lane ENUM('main') NOT NULL DEFAULT 'main',
    sequence_number BIGINT UNSIGNED NOT NULL,
    parent_entry_id VARCHAR(191) NULL,
    entry_kind ENUM('message.user','message.assistant','message.tool_call','message.tool_result','custom.external_context','compaction','pending.steering','pending.follow_up') NOT NULL,
    payload_json JSON NULL,
    payload_artifact_id BINARY(16) NULL,
    operation_id VARCHAR(191) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (entry_id),
    UNIQUE KEY uq_agent_session_entry_identity (tenant_id, session_key, stable_agent_node_key, entry_id),
    UNIQUE KEY uq_agent_session_entry_sequence (tenant_id, session_key, stable_agent_node_key, lane, sequence_number),
    KEY idx_agent_session_entry_chain (tenant_id, session_key, stable_agent_node_key, lane, sequence_number),
    KEY idx_agent_session_entry_operation (tenant_id, operation_id),
    CONSTRAINT chk_agent_session_entry_payload CHECK ((payload_json IS NOT NULL) <> (payload_artifact_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_session_registers (
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    lane ENUM('main') NOT NULL DEFAULT 'main',
    bundle_hash VARCHAR(128) NOT NULL,
    definition_hash VARCHAR(128) NOT NULL,
    model_version VARCHAR(255) NOT NULL,
    core_contract_version VARCHAR(32) NOT NULL,
    leaf_entry_id VARCHAR(191) NULL,
    open_operation_id VARCHAR(191) NULL,
    state_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
    terminal_state VARCHAR(64) NULL,
    operation_json JSON NULL,
    register_json JSON NOT NULL,
    retention_json JSON NULL,
    lease_expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, session_key, stable_agent_node_key),
    KEY idx_agent_session_register_application (tenant_id, application_id, updated_at),
    KEY idx_agent_session_register_open (tenant_id, open_operation_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_session_operations (
    operation_id VARCHAR(191) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    fencing_token BIGINT UNSIGNED NOT NULL,
    expected_state_version BIGINT UNSIGNED NOT NULL,
    phase VARCHAR(64) NOT NULL,
    operation_json JSON NOT NULL,
    input_hash CHAR(64) NOT NULL,
    bundle_hash VARCHAR(128) NOT NULL,
    model_version VARCHAR(255) NOT NULL,
    registry_hash CHAR(64) NOT NULL,
    replay_policy VARCHAR(32) NOT NULL,
    deadline_at TIMESTAMP(6) NOT NULL,
    recovery_action VARCHAR(128) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (operation_id),
    KEY idx_agent_session_operation_phase (tenant_id, session_key, stable_agent_node_key, phase, updated_at),
    KEY idx_agent_session_operation_recovery (tenant_id, session_key, stable_agent_node_key, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_session_usages (
    usage_id VARCHAR(191) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    operation_id VARCHAR(191) NOT NULL,
    effect_id VARCHAR(191) NOT NULL,
    usage_kind ENUM('model','compaction','tool','memory') NOT NULL,
    resource_reference VARCHAR(255) NULL,
    input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cache_read_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cache_write_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_currency CHAR(3) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (usage_id),
    UNIQUE KEY uq_agent_session_usage_effect (tenant_id, operation_id, effect_id, usage_kind),
    KEY idx_agent_session_usage_session (tenant_id, session_key, stable_agent_node_key, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_session_pending_entries (
    entry_id VARCHAR(191) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    execution_id BINARY(16) NULL,
    node_execution_id BINARY(16) NULL,
    attempt_id BINARY(16) NULL,
    lane ENUM('main') NOT NULL DEFAULT 'main',
    queue_kind ENUM('steering','follow_up','retry') NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    payload_json JSON NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    status ENUM('pending','consumed','cancelled') NOT NULL DEFAULT 'pending',
    wake_command_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    consumed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (entry_id),
    UNIQUE KEY uq_agent_session_pending_idempotency (tenant_id, session_key, stable_agent_node_key, idempotency_key),
    KEY idx_agent_session_pending_queue (tenant_id, session_key, stable_agent_node_key, status, sequence_number),
    KEY idx_agent_session_pending_wakeup (status, queue_kind, wake_command_id, sequence_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_subject_memory_audit (
    audit_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    authenticated_subject_id BINARY(16) NOT NULL,
    memory_resource_version_id BINARY(16) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    operation_id VARCHAR(191) NULL,
    result_hash CHAR(64) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (audit_id),
    KEY idx_agent_subject_memory_scope (tenant_id, application_id, authenticated_subject_id, memory_resource_version_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_subject_memory_clears (
    clear_id BINARY(16) NOT NULL,
    audit_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    authenticated_subject_id BINARY(16) NOT NULL,
    memory_resource_version_id BINARY(16) NOT NULL,
    scope_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    status ENUM('requested','applied','failed') NOT NULL DEFAULT 'requested',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    applied_at TIMESTAMP(6) NULL,
    last_error VARCHAR(1000) NULL,
    PRIMARY KEY (clear_id),
    UNIQUE KEY uq_agent_subject_memory_clear_idempotency (tenant_id, idempotency_key),
    KEY idx_agent_subject_memory_clear_scope (tenant_id, application_id, authenticated_subject_id, memory_resource_version_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE api_key_admission (
    key_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    key_prefix VARCHAR(48) NOT NULL,
    key_name VARCHAR(160) NOT NULL,
    secret_hash BINARY(32) NOT NULL,
    admission_epoch BIGINT UNSIGNED NOT NULL,
    status ENUM('active','revoked') NOT NULL,
    expires_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (key_id),
    UNIQUE KEY uq_api_key_admission_prefix (key_prefix),
    KEY idx_api_key_admission_app (tenant_id, application_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_heads (
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    bundle_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    admission_epoch BIGINT UNSIGNED NOT NULL,
    version BIGINT UNSIGNED NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, application_id),
    UNIQUE KEY uq_deployment_head_bundle (bundle_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_bundles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    schema_version SMALLINT UNSIGNED NOT NULL,
    content_hash CHAR(71) NOT NULL,
    signature VARBINARY(128) NOT NULL,
    payload_json JSON NOT NULL,
    status ENUM('prepared','active','superseded','disabled') NOT NULL DEFAULT 'prepared',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_deployment_bundle_sequence (tenant_id, application_id, sequence_number),
    UNIQUE KEY uq_deployment_bundle_hash (tenant_id, content_hash),
    CONSTRAINT chk_bundle_schema_version CHECK (schema_version = 2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_invocations (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    session_id BINARY(16) NULL,
    workflow_version_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NULL,
    caller_type ENUM('user', 'api_key', 'webhook', 'schedule') NOT NULL,
    caller_id BINARY(16) NULL,
    request_hash CHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    status ENUM('queued', 'running', 'completed', 'failed', 'cancelled') NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_invocation_idempotency (tenant_id, application_id, caller_type, caller_id, idempotency_key),
    KEY idx_invocations_session (tenant_id, session_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_message_parts (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    message_id BINARY(16) NOT NULL,
    part_index INT UNSIGNED NOT NULL,
    part_type ENUM('text', 'json', 'image', 'audio', 'file', 'tool_call', 'tool_result') NOT NULL,
    content_json JSON NULL,
    artifact_id BINARY(16) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_message_part_index (message_id, part_index)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_messages (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    session_id BINARY(16) NOT NULL,
    invocation_id BINARY(16) NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    role ENUM('user', 'assistant', 'system', 'tool') NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_message_sequence (tenant_id, session_id, sequence_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE schedule_bindings (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    bundle_id BINARY(16) NOT NULL,
    schedule_json JSON NOT NULL,
    status ENUM('active','disabled') NOT NULL,
    next_fire_at TIMESTAMP(6) NULL,
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_schedule_claim (status, next_fire_at, locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_session_contexts (
    tenant_id BINARY(16) NOT NULL,
    application_deployment_id BINARY(16) NOT NULL,
    session_id BINARY(16) NOT NULL,
    context_json JSON NOT NULL,
    context_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, application_deployment_id, session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_session_version_history (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    session_id BINARY(16) NOT NULL,
    from_workflow_version_id BINARY(16) NULL,
    to_workflow_version_id BINARY(16) NOT NULL,
    changed_by BINARY(16) NOT NULL,
    changed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_session_version_history (tenant_id, session_id, changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_sessions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    application_deployment_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NULL,
    version_policy ENUM('pinned', 'follow_deployment', 'manual_upgrade') NOT NULL,
    external_user_id VARCHAR(255) NULL,
    title VARCHAR(255) NULL,
    status ENUM('active', 'closed') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_by_user_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_application_sessions (tenant_id, application_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE webhook_bindings (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    bundle_id BINARY(16) NOT NULL,
    public_id VARCHAR(64) NOT NULL,
    secret_hash BINARY(32) NOT NULL,
    status ENUM('active','disabled') NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_webhook_binding_public_id (public_id),
    KEY idx_webhook_binding_app (tenant_id, application_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_routes (
    application_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    route_key VARCHAR(160) NOT NULL,
    active_bundle_id BINARY(16) NULL,
    admission_epoch BIGINT UNSIGNED NOT NULL,
    status ENUM('active','disabled') NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (application_id),
    UNIQUE KEY uq_application_route (tenant_id, route_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_decisions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    approval_task_id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NOT NULL,
    action_type ENUM('claim', 'release', 'reassign', 'approve', 'reject', 'cancel', 'timeout') NOT NULL,
    input_json JSON NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_approval_actions_task (tenant_id, approval_task_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_candidates (
    tenant_id BINARY(16) NOT NULL,
    approval_task_id BINARY(16) NOT NULL,
    candidate_type ENUM('user', 'role', 'department') NOT NULL,
    candidate_id BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, approval_task_id, candidate_type, candidate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_tasks (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NULL,
    request_payload_json JSON NULL,
    status ENUM('pending', 'claimed', 'approved', 'rejected', 'cancelled', 'timed_out') NOT NULL DEFAULT 'pending',
    claimed_by BINARY(16) NULL,
    claimed_at TIMESTAMP(6) NULL,
    resume_status ENUM('not_requested', 'pending', 'succeeded', 'blocked_runtime', 'failed') NOT NULL DEFAULT 'not_requested',
    deadline_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_approval_tasks_inbox (tenant_id, status, deadline_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE artifact_references (
    tenant_id BINARY(16) NOT NULL,
    artifact_id BINARY(16) NOT NULL,
    owner_type VARCHAR(64) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    reference_role VARCHAR(64) NOT NULL,
    retention_until TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, artifact_id, owner_type, owner_id, reference_role),
    KEY idx_artifact_reference_owner (tenant_id, owner_type, owner_id),
    KEY idx_artifact_reference_retention (tenant_id, artifact_id, retention_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE artifacts (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_artifacts_storage_key (storage_key),
    KEY idx_artifacts_tenant_created (tenant_id, created_at),
    KEY idx_artifacts_tenant_hash (tenant_id, sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_events (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(128) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    request_id BINARY(16) NOT NULL,
    detail_json JSON NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_audit_tenant_time (tenant_id, occurred_at),
    KEY idx_audit_target (tenant_id, target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE checkpoint_artifacts (
    tenant_id BINARY(16) NOT NULL,
    checkpoint_id BINARY(16) NOT NULL,
    artifact_id BINARY(16) NOT NULL,
    role ENUM('state', 'input', 'output', 'binary', 'log') NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (checkpoint_id, artifact_id, role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE checkpoints (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    checkpoint_type ENUM('execution_start', 'node_completed', 'node_suspended', 'manual') NOT NULL,
    state_hash VARCHAR(96) NOT NULL,
    payload_json JSON NULL,
    payload_artifact_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_checkpoint_sequence (execution_id, sequence_number),
    KEY idx_checkpoint_timeline (tenant_id, execution_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE credential_secret_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    credential_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    algorithm VARCHAR(32) NOT NULL,
    key_id VARCHAR(64) NOT NULL,
    nonce VARBINARY(32) NOT NULL,
    ciphertext MEDIUMBLOB NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_credential_secret_version (tenant_id, credential_id, version_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE credentials (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    credential_type ENUM('api_key', 'bearer', 'basic', 'custom_json') NOT NULL,
    storage_mode ENUM('local_encrypted', 'external_reference') NOT NULL DEFAULT 'local_encrypted',
    masked_hint VARCHAR(32) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    current_secret_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    owner_department_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_credentials_tenant_status (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_history (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    deployment_id BINARY(16) NOT NULL,
    action ENUM('published', 'superseded', 'rolled_back') NOT NULL,
    actor_user_id BINARY(16) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_deployment_history (tenant_id, workflow_id, environment_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_case_results (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    source_case_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    status ENUM('passed', 'failed', 'error', 'cancelled') NOT NULL,
    score DECIMAL(12,6) NULL,
    detail_json JSON NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_case_result (tenant_id, evaluation_run_id, source_case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_comparisons (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    baseline_run_id BINARY(16) NOT NULL,
    candidate_run_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_metrics (
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    metric_key VARCHAR(128) NOT NULL,
    metric_value DECIMAL(24,8) NOT NULL,
    detail_json JSON NULL,
    PRIMARY KEY (tenant_id, evaluation_run_id, metric_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_rule_results (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_case_id BINARY(16) NOT NULL,
    profile_rule_id BINARY(16) NOT NULL,
    evaluator_command_id BINARY(16) NULL,
    evaluator_execution_id BINARY(16) NULL,
    status ENUM('queued','running','passed','failed','error','cancelled') NOT NULL,
    passed BOOLEAN NULL,
    score DECIMAL(12,6) NULL,
    detail_json JSON NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_case_rule (tenant_id, evaluation_run_case_id, profile_rule_id),
    KEY idx_evaluation_rule_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_run_cases (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    source_case_id BINARY(16) NOT NULL,
    target_command_id BINARY(16) NOT NULL,
    target_execution_id BINARY(16) NULL,
    status ENUM('queued','running','scoring','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
    actual_output_json JSON NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_run_case (tenant_id, evaluation_run_id, source_case_id),
    UNIQUE KEY uq_evaluation_case_command (target_command_id),
    KEY idx_evaluation_case_status (tenant_id, evaluation_run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    dataset_version_id BINARY(16) NOT NULL,
    evaluation_profile_version_id BINARY(16) NOT NULL,
    parameters_json JSON NOT NULL,
    status ENUM('created', 'queued', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'created',
    created_by BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_evaluation_runs (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_edge_deliveries (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    connection_id VARCHAR(128) NOT NULL,
    source_node_execution_id BINARY(16) NOT NULL,
    source_port VARCHAR(128) NOT NULL,
    target_node_id VARCHAR(128) NOT NULL,
    target_port VARCHAR(128) NOT NULL,
    target_generation INT UNSIGNED NOT NULL,
    delivery_kind ENUM('data', 'closed_without_data') NOT NULL,
    item_count INT UNSIGNED NOT NULL DEFAULT 0,
    payload_json JSON NULL,
    payload_artifact_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_edge_delivery_sequence (execution_id, sequence_number),
    KEY idx_edge_delivery_frontier (tenant_id, execution_id, target_node_id, target_generation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_end_deliveries (
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    source_node_execution_id BINARY(16) NOT NULL,
    source_node_id VARCHAR(128) NOT NULL,
    source_port VARCHAR(128) NOT NULL,
    target_port ENUM('main', 'error') NOT NULL,
    payload_json JSON NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (execution_id, sequence_number),
    KEY idx_end_delivery_terminal (tenant_id, execution_id, target_port, sequence_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_events (
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    summary_json JSON NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (tenant_id, execution_id, sequence_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_outbox (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NULL,
    attempt_id BINARY(16) NULL,
    message_type ENUM('dispatch_node', 'runtime_event', 'resume', 'cancel') NOT NULL,
    capability ENUM('builtin', 'declarative_http', 'remote_action') NULL,
    payload_json JSON NOT NULL,
    status ENUM('pending', 'published', 'failed') NOT NULL DEFAULT 'pending',
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    published_at TIMESTAMP(6) NULL,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_execution_outbox_pending (status, available_at, locked_until, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_resume_tokens (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    resume_kind ENUM('time', 'webhook', 'form', 'approval') NOT NULL,
    status ENUM('active', 'used', 'expired', 'cancelled') NOT NULL DEFAULT 'active',
    idempotency_key VARCHAR(192) NULL,
    expires_at TIMESTAMP(6) NULL,
    used_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resume_token_hash (token_hash),
    UNIQUE KEY uq_resume_node_kind (node_execution_id, resume_kind),
    KEY idx_resume_token_expiry (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE execution_snapshots (
    execution_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    definition_json JSON NOT NULL,
    compiled_ir_json JSON NOT NULL,
    compiled_ir_hash VARCHAR(96) NOT NULL,
    compiler_version VARCHAR(64) NOT NULL,
    resource_snapshot_json JSON NOT NULL,
    runtime_settings_json JSON NOT NULL,
    state_hash VARCHAR(96) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE invocation_events (
    tenant_id BINARY(16) NOT NULL,
    invocation_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, invocation_id, sequence_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE item_lineage (
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    delivery_id BINARY(16) NOT NULL,
    target_item_index INT UNSIGNED NOT NULL,
    source_node_execution_id BINARY(16) NOT NULL,
    source_run_index INT UNSIGNED NOT NULL,
    source_output_index INT UNSIGNED NOT NULL,
    source_item_index INT UNSIGNED NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (delivery_id, target_item_index, source_node_execution_id, source_output_index, source_item_index),
    KEY idx_item_lineage_execution (tenant_id, execution_id, source_node_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE node_attempts (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_number INT UNSIGNED NOT NULL,
    status ENUM('queued', 'running', 'suspended', 'succeeded', 'failed', 'cancelled', 'timed_out', 'lease_expired') NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    lease_token BINARY(16) NULL,
    worker_instance_id VARCHAR(160) NULL,
    fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
    locked_until TIMESTAMP(6) NULL,
    deadline_at TIMESTAMP(6) NULL,
    input_json JSON NULL,
    output_json JSON NULL,
    log_artifact_id BINARY(16) NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    started_at TIMESTAMP(6) NULL,
    ended_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_attempt_number (node_execution_id, attempt_number),
    UNIQUE KEY uq_node_attempt_idempotency (tenant_id, idempotency_key),
    KEY idx_node_attempt_execution (tenant_id, execution_id, created_at),
    KEY idx_node_attempt_lease (status, locked_until, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE node_executions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    node_name VARCHAR(160) NOT NULL,
    node_type VARCHAR(128) NOT NULL,
    node_version INT UNSIGNED NOT NULL,
    generation INT UNSIGNED NOT NULL,
    activation_slot INT UNSIGNED NOT NULL,
    run_index INT UNSIGNED NOT NULL,
    iteration_index INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('ready', 'queued', 'running', 'waiting', 'succeeded', 'failed', 'skipped', 'cancelled', 'timed_out') NOT NULL,
    capability ENUM('builtin', 'declarative_http', 'remote_action') NOT NULL,
    side_effect_level ENUM('none', 'idempotent', 'reversible', 'irreversible') NOT NULL DEFAULT 'none',
    input_json JSON NULL,
    output_json JSON NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    started_at TIMESTAMP(6) NULL,
    ended_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_execution_activation (execution_id, node_id, generation, activation_slot),
    KEY idx_node_execution_ready (tenant_id, status, capability, created_at),
    KEY idx_node_execution_list (tenant_id, execution_id, run_index, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE node_invocation_handles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    lease_token BINARY(16) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    handle_kind ENUM('credential', 'artifact', 'cancellation') NOT NULL,
    resource_id BINARY(16) NULL,
    resource_version BIGINT UNSIGNED NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    consumed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_invocation_handle_token (token_hash),
    KEY idx_node_invocation_handle_expiry (expires_at, consumed_at),
    KEY idx_node_invocation_handle_attempt (tenant_id, attempt_id, handle_kind)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE notification_receipts (
    tenant_id BINARY(16) NOT NULL,
    notification_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    read_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, notification_id, user_id),
    KEY idx_notification_inbox (tenant_id, user_id, read_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE notifications (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    source_event_id BINARY(16) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    title_key VARCHAR(160) NOT NULL,
    body_key VARCHAR(160) NOT NULL,
    arguments_json JSON NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BINARY(16) NOT NULL,
    target_path VARCHAR(512) NOT NULL,
    tone ENUM('primary', 'success', 'warning', 'danger') NOT NULL DEFAULT 'primary',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_notification_source (tenant_id, source_event_id, notification_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE integration_event_log (
    event_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    aggregate_version BIGINT UNSIGNED NOT NULL,
    schema_version SMALLINT UNSIGNED NOT NULL,
    payload_json JSON NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (event_id),
    KEY idx_integration_event_export (tenant_id, occurred_at, event_id),
    CONSTRAINT chk_integration_event_schema CHECK (schema_version = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE command_receipts (
    command_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    command_hash CHAR(71) NOT NULL,
    status ENUM('applied','rejected') NOT NULL,
    result_json JSON NOT NULL,
    applied_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (command_id),
    UNIQUE KEY uq_command_receipt_idempotency (tenant_id, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_policy_projection (
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    hard_limit DECIMAL(24,6) NOT NULL,
    period_seconds BIGINT UNSIGNED NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, dimension_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_reservations (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    scope_type VARCHAR(64) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    status ENUM('active','settled','released','expired') NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    settled_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_quota_reservation_scope (tenant_id, dimension_key, scope_type, scope_id),
    KEY idx_quota_reservation_reaper (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_usage_ledger (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    scope_type VARCHAR(64) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_quota_usage_idempotency (tenant_id, idempotency_key),
    KEY idx_quota_usage_window (tenant_id, dimension_key, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_projection (
    grant_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    subject_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    operations_json JSON NOT NULL,
    policy_epoch BIGINT UNSIGNED NOT NULL,
    status ENUM('active','revoked') NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (grant_id),
    KEY idx_resource_grant_projection (tenant_id, subject_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resume_webhook_bindings (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    wait_subscription_id BINARY(16) NOT NULL,
    path_token_hash CHAR(64) NOT NULL,
    http_method ENUM('GET', 'POST') NOT NULL DEFAULT 'POST',
    authentication_config_hash CHAR(64) NULL,
    status ENUM('active', 'used', 'expired', 'cancelled') NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resume_webhook_path (path_token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_items (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    retention_run_id BINARY(16) NOT NULL,
    data_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    status ENUM('candidate','blocked','deleted','failed') NOT NULL,
    reason VARCHAR(255) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_retention_item_target (retention_run_id, data_type, target_id),
    KEY idx_retention_item_status (tenant_id, retention_run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_policy_projection (
    tenant_id BINARY(16) NOT NULL,
    data_type VARCHAR(64) NOT NULL,
    retention_days INT UNSIGNED NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_by BINARY(16) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, data_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    status ENUM('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
    requested_by BINARY(16) NOT NULL,
    candidate_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    deleted_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    started_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_retention_run_status (status, available_at, locked_until, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE runtime_calls (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    agent_run_id BINARY(16) NULL,
    iteration_index INT UNSIGNED NOT NULL DEFAULT 0,
    call_index INT UNSIGNED NOT NULL,
    call_kind ENUM('model', 'compaction', 'mcp_tool', 'rag', 'memory', 'sandbox') NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    resource_type VARCHAR(32) NULL,
    resource_id BINARY(16) NULL,
    resource_version_id BINARY(16) NULL,
    tool_name_snapshot VARCHAR(255) NULL,
    side_effect VARCHAR(32) NOT NULL DEFAULT 'none',
    status ENUM('reserved', 'sent', 'succeeded', 'failed', 'cancelled', 'unknown') NOT NULL,
    reserved_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reserved_output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reserved_cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cost_currency CHAR(3) NULL,
    usage_estimated BOOLEAN NOT NULL DEFAULT FALSE,
    response_artifact_id BINARY(16) NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ended_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_runtime_call_idempotency (tenant_id, idempotency_key),
    KEY idx_runtime_call_node (tenant_id, node_execution_id, iteration_index, call_index),
    KEY idx_runtime_call_resource (tenant_id, resource_type, resource_id, started_at),
    KEY idx_runtime_call_tool_execution (tenant_id, call_kind, resource_id, execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE runtime_commands (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    payload_json JSON NOT NULL,
    status ENUM('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    result_json JSON NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    completed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_runtime_command_idempotency (tenant_id, command_type, idempotency_key),
    KEY idx_runtime_commands_pending (status, available_at, locked_until, created_at),
    KEY idx_runtime_commands_aggregate (tenant_id, aggregate_type, aggregate_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE runtime_idempotency_keys (
    tenant_id BINARY(16) NOT NULL,
    scope VARCHAR(96) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    request_hash VARCHAR(96) NOT NULL,
    status ENUM('processing', 'completed', 'failed') NOT NULL,
    response_json JSON NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, scope, idempotency_key),
    KEY idx_runtime_idempotency_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE runtime_service_heartbeats (
    tenant_id BINARY(16) NOT NULL,
    service_type ENUM('coordinator', 'worker', 'sandbox', 'trace_writer') NOT NULL,
    instance_id VARCHAR(160) NOT NULL,
    status ENUM('ready', 'degraded', 'unavailable') NOT NULL,
    detail_json JSON NOT NULL,
    heartbeat_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (tenant_id, service_type, instance_id),
    KEY idx_runtime_heartbeat (tenant_id, service_type, heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_leases (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    worker_lease_token BINARY(16) NOT NULL,
    sandbox_id VARCHAR(255) NULL,
    lease_token_hash CHAR(64) NOT NULL,
    profile_version_id BINARY(16) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    status ENUM('creating', 'ready', 'running', 'interrupting', 'terminating', 'terminated', 'orphaned', 'failed') NOT NULL,
    endpoint_auth_key_id VARCHAR(64) NULL,
    endpoint_auth_nonce VARBINARY(32) NULL,
    endpoint_auth_ciphertext MEDIUMBLOB NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    heartbeat_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    termination_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    terminated_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sandbox_lease_idempotency (tenant_id, idempotency_key),
    UNIQUE KEY uq_sandbox_lease_token (lease_token_hash),
    KEY idx_sandbox_lease_reaper (status, expires_at, heartbeat_at),
    KEY idx_sandbox_lease_attempt (tenant_id, attempt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_workspaces (
    workspace_id BINARY(16) NOT NULL,
    identity_hash CHAR(64) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NULL,
    session_key VARCHAR(255) NOT NULL,
    stable_agent_node_key VARCHAR(255) NOT NULL,
    profile_version_id VARCHAR(191) NOT NULL,
    profile_json JSON NOT NULL,
    sandbox_id VARCHAR(255) NULL,
    status ENUM('creating','active','releasing','expired','unknown_outcome') NOT NULL DEFAULT 'creating',
    lease_id BINARY(16) NULL,
    attempt_id BINARY(16) NULL,
    worker_id BINARY(16) NULL,
    fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
    lease_expires_at TIMESTAMP(6) NULL,
    workspace_expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (workspace_id),
    UNIQUE KEY uq_sandbox_workspace_identity (identity_hash),
    KEY idx_sandbox_workspace_reaper (status, workspace_expires_at, lease_expires_at),
    KEY idx_sandbox_workspace_tenant (tenant_id, application_id, session_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_process_sessions (
    process_session_id BINARY(16) NOT NULL,
    identity_hash CHAR(64) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    agent_run_id BINARY(16) NOT NULL,
    mcp_server_version_id BINARY(16) NOT NULL,
    sandbox_profile_version_id BINARY(16) NOT NULL,
    profile_json JSON NOT NULL,
    command_json JSON NOT NULL,
    credential_refs_json JSON NOT NULL,
    sandbox_id VARCHAR(255) NULL,
    provider_operation_id VARCHAR(255) NULL,
    provider_output_offset BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('acquiring','starting','running','interrupting','terminating','exited','failed','unknown_outcome','expired') NOT NULL,
    lease_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    worker_id BINARY(16) NOT NULL,
    fencing_token BIGINT UNSIGNED NOT NULL,
    lease_expires_at TIMESTAMP(6) NOT NULL,
    process_expires_at TIMESTAMP(6) NOT NULL,
    exit_code BIGINT NULL,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (process_session_id),
    UNIQUE KEY uq_sandbox_process_identity (identity_hash),
    KEY idx_sandbox_process_reaper (status, process_expires_at, lease_expires_at),
    KEY idx_sandbox_process_run (tenant_id, agent_run_id, mcp_server_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_process_frames (
    process_session_id BINARY(16) NOT NULL,
    sequence BIGINT UNSIGNED NOT NULL,
    stream ENUM('stdout','stderr') NOT NULL,
    payload_json JSON NULL,
    artifact_id BINARY(16) NULL,
    truncated BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (process_session_id, sequence),
    KEY idx_sandbox_process_frame_artifact (artifact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE side_effect_confirmations (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    checkpoint_id BINARY(16) NULL,
    actor_user_id BINARY(16) NOT NULL,
    decision ENUM('execute', 'reuse_output', 'dry_run') NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    detail_json JSON NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_side_effect_decision (tenant_id, execution_id, node_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tenant_policy_projection (
    tenant_id BINARY(16) NOT NULL,
    policy_version BIGINT UNSIGNED NOT NULL,
    policy_json JSON NOT NULL,
    applied_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tenant_admission (
    tenant_id BINARY(16) NOT NULL,
    status ENUM('active','disabled') NOT NULL,
    admission_epoch BIGINT UNSIGNED NOT NULL,
    policy_version BIGINT UNSIGNED NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id),
    CONSTRAINT chk_tenant_admission_epoch CHECK (admission_epoch > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trace_outbox (
    event_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    payload_json JSON NOT NULL,
    status ENUM('pending','streamed','failed') NOT NULL DEFAULT 'pending',
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    fencing_token BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (event_id),
    KEY idx_trace_outbox_claim (status, available_at, locked_until, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trigger_bindings (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    application_deployment_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    trigger_kind ENUM('webhook','schedule','poll','lifecycle') NOT NULL,
    configuration_json JSON NOT NULL,
    status ENUM('activating','active','deactivating','disabled','failed') NOT NULL,
    next_poll_at TIMESTAMP(6) NULL,
    last_poll_at TIMESTAMP(6) NULL,
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_trigger_binding_node (tenant_id, application_deployment_id, node_id, trigger_kind),
    KEY idx_trigger_binding_scan (status, trigger_kind, next_poll_at, locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE wait_subscriptions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    resume_token_id BINARY(16) NOT NULL,
    wait_kind ENUM('duration', 'datetime', 'webhook', 'form', 'approval') NOT NULL,
    status ENUM('waiting', 'resumed', 'timed_out', 'cancelled') NOT NULL DEFAULT 'waiting',
    wake_at TIMESTAMP(6) NULL,
    timeout_at TIMESTAMP(6) NULL,
    authentication_mode ENUM('none', 'header', 'basic', 'signed') NOT NULL DEFAULT 'signed',
    response_mode ENUM('accepted', 'last_node') NOT NULL DEFAULT 'accepted',
    payload_schema_json JSON NULL,
    resumed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_wait_node (node_execution_id),
    KEY idx_wait_scheduler (status, wake_at, timeout_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE worker_capabilities (
    instance_id VARCHAR(160) NOT NULL,
    capability VARCHAR(64) NOT NULL,
    node_protocol_version VARCHAR(32) NOT NULL,
    ir_schema_versions_json JSON NOT NULL,
    compiler_version_min VARCHAR(64) NOT NULL,
    compiler_version_max VARCHAR(64) NOT NULL,
    manifest_hashes_json JSON NOT NULL,
    status ENUM('ready','draining','unavailable') NOT NULL DEFAULT 'ready',
    heartbeat_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (instance_id, capability),
    KEY idx_worker_capability_ready (capability, status, heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE worker_leases (
    node_attempt_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    lease_token BINARY(16) NOT NULL,
    worker_instance_id VARCHAR(160) NOT NULL,
    capability ENUM('builtin', 'declarative_http', 'remote_action') NOT NULL,
    acquired_at TIMESTAMP(6) NOT NULL,
    heartbeat_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    released_at TIMESTAMP(6) NULL,
    PRIMARY KEY (node_attempt_id),
    UNIQUE KEY uq_worker_lease_token (lease_token),
    KEY idx_worker_lease_reaper (expires_at, released_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_context_patches (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    patch_index INT UNSIGNED NOT NULL,
    operation_key VARCHAR(32) NOT NULL,
    context_path VARCHAR(512) NOT NULL,
    value_json JSON NOT NULL,
    context_version_before BIGINT UNSIGNED NOT NULL,
    context_version_after BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_context_patch (tenant_id, node_execution_id, patch_index),
    KEY idx_workflow_context_patch_execution (tenant_id, execution_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_deployment_heads (
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    active_deployment_id BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, workflow_id, environment_id),
    UNIQUE KEY uq_workflow_active_deployment (active_deployment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_deployments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    status ENUM('active', 'superseded', 'rolled_back') NOT NULL DEFAULT 'active',
    source ENUM('publish', 'rollback') NOT NULL DEFAULT 'publish',
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_deployment_sequence (tenant_id, workflow_id, environment_id, sequence_number),
    KEY idx_workflow_deployment_history (tenant_id, workflow_id, environment_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_executions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    invocation_id BINARY(16) NULL,
    session_id BINARY(16) NULL,
    trace_id BINARY(16) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    status ENUM('created', 'queued', 'running', 'waiting', 'waiting_approval', 'suspended', 'succeeded', 'failed', 'cancelled', 'timed_out') NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6) NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_execution_trace (tenant_id, trace_id),
    KEY idx_workflow_executions_list (tenant_id, status, started_at),
    KEY idx_workflow_executions_workflow (tenant_id, workflow_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE service_identity_projection (
    identity_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    policy_epoch BIGINT UNSIGNED NOT NULL,
    status ENUM('active','disabled') NOT NULL,
    capabilities_json JSON NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (identity_id),
    KEY idx_service_identity_workflow (tenant_id, workflow_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
