-- `agent_runs.attempt_id` and its lookup index are part of the V2 empty-database
-- contract in 0001_initial.sql.  Keep this migration as a recorded no-op so
-- the historical SQLx sequence remains stable without attempting to add the
-- column a second time on a freshly bootstrapped runtime database.
