apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web.yaml
  - platform-api.yaml
  - platform-api-migration.yaml
  - trigger-gateway.yaml
  - workflow-coordinator.yaml
  - workflow-worker.yaml
  - sandbox-manager.yaml
  - trace-writer.yaml
  - trace-writer-migration.yaml
