CREATE TABLE node_invocation_handles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    node_execution_id BINARY(16) NOT NULL,
    attempt_id BINARY(16) NOT NULL,
    lease_token BINARY(16) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    handle_kind ENUM('credential', 'artifact', 'cancellation') NOT NULL,
    resource_id BINARY(16) NULL,
    resource_version BIGINT UNSIGNED NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    consumed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_invocation_handle_token (token_hash),
    KEY idx_node_invocation_handle_expiry (expires_at, consumed_at),
    KEY idx_node_invocation_handle_attempt (tenant_id, attempt_id, handle_kind),
    CONSTRAINT fk_node_invocation_handle_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_node_invocation_handle_execution FOREIGN KEY (execution_id) REFERENCES workflow_executions(id),
    CONSTRAINT fk_node_invocation_handle_node FOREIGN KEY (node_execution_id) REFERENCES node_executions(id),
    CONSTRAINT fk_node_invocation_handle_attempt FOREIGN KEY (attempt_id) REFERENCES node_attempts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
