CREATE TABLE resource_grant_requests (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    workflow_service_identity_id BINARY(16) NOT NULL,
    primary_resource_type VARCHAR(32) NOT NULL,
    primary_resource_id BINARY(16) NOT NULL,
    primary_resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    source_node_id VARCHAR(128) NULL,
    source_revision BIGINT UNSIGNED NULL,
    request_message VARCHAR(1000) NULL,
    dependency_hash VARCHAR(80) NOT NULL,
    open_dedupe_key VARCHAR(80) NULL,
    status ENUM('pending', 'approved', 'rejected', 'cancelled', 'stale') NOT NULL DEFAULT 'pending',
    requested_by BINARY(16) NOT NULL,
    resolved_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_open (tenant_id, open_dedupe_key),
    KEY idx_resource_grant_request_inbox (tenant_id, status, updated_at),
    KEY idx_resource_grant_request_workflow (tenant_id, workflow_id, status),
    CONSTRAINT fk_resource_grant_request_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_resource_grant_request_workflow FOREIGN KEY (workflow_id) REFERENCES workflows(id),
    CONSTRAINT fk_resource_grant_request_identity FOREIGN KEY (workflow_service_identity_id) REFERENCES workflow_service_identities(id),
    CONSTRAINT fk_resource_grant_request_user FOREIGN KEY (requested_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_request_items (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    request_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    required_by_resource_id BINARY(16) NULL,
    owner_department_id BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_item (request_id, resource_type, resource_id, operation_key),
    KEY idx_resource_grant_request_item_department (tenant_id, owner_department_id, request_id),
    CONSTRAINT fk_resource_grant_request_item_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_resource_grant_request_item_request FOREIGN KEY (request_id) REFERENCES resource_grant_requests(id),
    CONSTRAINT fk_resource_grant_request_item_department FOREIGN KEY (owner_department_id) REFERENCES departments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_request_reviews (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    request_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
    reviewed_by BINARY(16) NULL,
    review_comment VARCHAR(1000) NULL,
    reviewed_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_review (request_id, owner_department_id),
    KEY idx_resource_grant_request_review_inbox (tenant_id, owner_department_id, status, updated_at),
    CONSTRAINT fk_resource_grant_request_review_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_resource_grant_request_review_request FOREIGN KEY (request_id) REFERENCES resource_grant_requests(id),
    CONSTRAINT fk_resource_grant_request_review_department FOREIGN KEY (owner_department_id) REFERENCES departments(id),
    CONSTRAINT fk_resource_grant_request_review_user FOREIGN KEY (reviewed_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
