[package]
name = "workflow-worker"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
agentx-application.workspace = true
agentx-domain.workspace = true
agentx-infrastructure.workspace = true
agentx-node-protocol.workspace = true
agentx-runtime.workspace = true
agentx-runtime-rpc.workspace = true
agentx-service-kit.workspace = true
anyhow.workspace = true
axum.workspace = true
futures.workspace = true
reqwest.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
secrecy.workspace = true
sha2.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
object_store.workspace = true
testcontainers = "0.25"
