apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentx-e2e
resources:
  - ../full
patches:
  - target:
      kind: Namespace
      name: agentx
    patch: |-
      - op: replace
        path: /metadata/name
        value: agentx-e2e
  - target:
      kind: ConfigMap
      name: agentx-config
    patch: |-
      - op: replace
        path: /data/AGENTX_SANDBOX_MAX_ACTIVE_PER_TENANT
        value: "1"
