const translations = {
  loading: 'Loading trace…', unavailable: 'Trace is temporarily unavailable', delayed: 'Trace is syncing. Showing spans received so far.', degraded: 'Trace ingestion conflicts were detected; diagnostics may be incomplete.',
  search: 'Search spans, IDs, or errors', filterKind: 'Filter span kind', allKinds: 'All kinds', errorsOnly: 'Errors only', expandAll: 'Expand all', zoom: 'Zoom', loaded: '{{loaded}} / {{total}} loaded', loadMore: 'Load more', noMatches: 'No matching spans',
  tree: 'Trace hierarchy waterfall', hierarchy: 'Call hierarchy', status: 'Status', duration: 'Duration', totalDuration: 'Total duration', timeline: 'Timeline', expand: 'Expand', collapse: 'Collapse', selectSpan: 'Select a span to inspect details', loadingDetail: 'Loading span details…',
  overview: 'Overview', events: 'Events', raw: 'Raw', startedAt: 'Started at', tokens: 'Input / output tokens', cost: 'Cost', lifecycleOnly: 'This lifecycle span has no business content.', diagnosticUnavailable: 'Trace is unavailable. Authoritative node input and output remain visible.',
  finalOutput: 'Workflow final output', structuredFinalOutput: 'Structured final output', showFinalJson: 'Show final JSON', hideFinalJson: 'Hide final JSON', workflowInput: 'Workflow input', workflowOutput: 'Workflow output',
  authoritativeDataUnavailable: 'Authoritative Runtime execution data is unavailable.', loadingExecutionData: 'Loading authoritative Runtime execution data…', authoritativeInputEmpty: 'Runtime did not record business input.', authoritativeOutputEmpty: 'Runtime has not produced business output.',
  businessInputAndParameters: 'Input and resolved parameters', upstreamItems: 'Upstream items', resolvedParameters: 'Resolved parameters', semanticOutput: 'Semantic output', internalProcess: 'Internal process', internalProcessHint: 'Collapsed by default for diagnostics', syncing: 'Trace is syncing…', noInternalSpans: 'This node has no internal calls.', noResolvedParameters: 'This node has no resolved-parameters event.', noDiagnosticContent: 'This span has no diagnostic content.', noBusinessContent: 'No business content.', noNodeRuns: 'This execution has no run for the selected node.',
  itemCount: '{{count}} items', itemIndex: 'Item {{index}}', rawItem: 'Raw item / lineage / binary', emptyObject: 'Empty object', downloadArtifact: 'View / download artifact', usageValue: '{{input}} input · {{output}} output · {{total}} total', runLabel: 'run {{run}} · iteration {{iteration}}',
  views: { label: 'Trace view', nodes: 'Node view', waterfall: 'Advanced waterfall', nodesHint: 'Business nodes and semantic input/output by default', waterfallHint: 'Low-level span timeline and full diagnostics' },
  boundaries: { start: 'Start', startDescription: 'Start Boundary · Workflow input', end: 'End', endDescription: 'End Boundary · Workflow output' },
  waitApproval: 'Approval · {{title}}', waitGeneric: 'Wait · {{title}}',
  kinds: { execution: 'Execution', boundary: 'Boundary', node: 'Node', attempt: 'Attempt', agent_run: 'Agent run', agent_iteration: 'Agent iteration', runtime_call: 'Runtime call', sandbox: 'Sandbox', wait: 'Wait / approval' },
  contentKinds: { workflow_input: 'Workflow input', workflow_output: 'Workflow output', node_input: 'Node input', node_output: 'Node output', attempt_input: 'Attempt input', attempt_output: 'Attempt output', resolved_parameters: 'Resolved parameters', runtime_request: 'Provider / Runtime request', runtime_response: 'Provider / Runtime response', agent_input: 'Agent input', agent_output: 'Agent output', iteration_input: 'Iteration input', iteration_output: 'Iteration output', sandbox_request: 'Sandbox request', sandbox_response: 'Sandbox response', wait_request: 'Wait request', wait_response: 'Wait response', conversion_record: 'String conversion record' },
} as const
export default translations
