import { expect, type Browser, type Locator, type Page, test } from '@playwright/test'

const company = 'Agentx E2E'
const adminPassword = 'agentx-e2e-admin-password'

async function dialog(page: Page, title: string) {
  const value = page.getByRole('dialog', { name: title })
  await expect(value).toBeVisible()
  return value
}

async function field(container: Locator, label: string) {
  return container.locator('label').filter({ hasText: label }).locator('input, textarea').first()
}

async function select(container: Locator, label: string, option: string) {
  await container.getByRole('combobox', { name: label, exact: true }).click()
  await container.page().getByRole('option', { name: option, exact: true }).click()
}

async function submit(container: Locator, name: string) {
  await container.getByRole('button', { name, exact: true }).click()
  await expect(container).toBeHidden()
}

async function fillMonaco(page: Page, scope: Locator, value: string) {
  const editor = scope.getByRole('textbox', { name: 'Editor content' })
  await expect(editor).toBeVisible({ timeout: 30_000 })
  await editor.focus()
  await page.keyboard.press('Control+A')
  await page.keyboard.press('Backspace')
  await page.keyboard.insertText(value)
  await expect.poll(async () => {
    const text = (await scope.locator('.view-lines').textContent())?.replaceAll('\u00a0', ' ').trim()
    try { return JSON.parse(text ?? '') } catch { return null }
  }).toEqual(JSON.parse(value))
}

async function grantResource(page: Page, name: string, resourceType: string, subject: 'workflow' | 'department', operation = '使用') {
  await page.getByRole('tab', { name: resourceType, exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: name }).filter({ hasText: resourceType }).first()
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '管理授权' }).click()
  const grant = page.getByRole('dialog', { name: new RegExp(`管理.*${name}.*授权`) })
  await expect(grant).toBeVisible()
  if (subject === 'department') {
    await select(grant, '授权对象类型', '部门')
    await select(grant, '授权对象', company)
  } else {
    await select(grant, '授权对象类型', 'Workflow 运行身份')
    await select(grant, '授权对象', 'MCP Echo Workflow')
  }
  await select(grant, '操作', operation)
  await grant.getByRole('button', { name: '添加授权' }).click()
  await expect(grant.getByRole('button', { name: '撤销授权' })).toHaveCount(1)
  await grant.getByRole('button', { name: '取消' }).click()
  await expect(grant).toBeHidden()
}

async function bootstrap(page: Page) {
  await page.goto('/')
  await expect(page).toHaveURL(/\/setup$/)
  await page.getByLabel('公司名称').fill(company)
  await page.getByLabel('用户名').fill('admin')
  await page.getByLabel('管理员姓名').fill('E2E Admin')
  await page.getByLabel('密码').fill(adminPassword)
  await page.getByRole('button', { name: '初始化并进入工作台' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('main').getByText(new RegExp(company))).toBeVisible()
}

async function createWorkflow(page: Page) {
  await page.getByRole('link', { name: /^工作流/ }).click()
  await page.getByRole('button', { name: '新建工作流' }).click()
  const form = await dialog(page, '新建工作流')
  await (await field(form, '工作流名称')).fill('MCP Echo Workflow')
  await (await field(form, '描述')).fill('M2.1 browser acceptance workflow')
  await submit(form, '保存')
  await expect(page.getByRole('heading', { name: 'MCP Echo Workflow' })).toBeVisible()
}

async function createCredentialAndVerifyConflict(page: Page) {
  await page.getByRole('link', { name: '凭证', exact: true }).click()
  await page.getByRole('button', { name: '新建凭证' }).click()
  const create = await dialog(page, '新建凭证')
  await (await field(create, '名称')).fill('Echo Credential')
  await select(create, '凭证类型', 'Bearer Token')
  await (await field(create, '密钥内容')).fill('e2e-secret-never-returned')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Echo Credential/ }).getByRole('link', { name: '详情' }).click()

  const second = await page.context().newPage()
  await second.goto(page.url())
  await expect(second.getByRole('heading', { name: 'Echo Credential' })).toBeVisible()

  await page.getByRole('button', { name: '编辑', exact: true }).click()
  const rename = await dialog(page, '修改凭证名称')
  await (await field(rename, '名称')).fill('Echo Credential Renamed')
  await submit(rename, '保存')
  await expect(page.getByRole('heading', { name: 'Echo Credential Renamed' })).toBeVisible()

  await second.getByRole('button', { name: '编辑', exact: true }).click()
  const stale = await dialog(second, '修改凭证名称')
  await (await field(stale, '名称')).fill('Stale Rename')
  await stale.getByRole('button', { name: '保存', exact: true }).click()
  await expect(stale.getByText(/Credential changed|凭证已被修改|CONFLICT/i)).toBeVisible()
  await second.close()
  await page.goto('/credentials')
}

async function createAndReviseModel(page: Page) {
  await page.getByRole('link', { name: '模型服务', exact: true }).click()
  await page.getByRole('button', { name: '接入模型' }).click()
  const create = await dialog(page, '接入模型')
  await (await field(create, 'Provider 名称')).fill('E2E Provider')
  await (await field(create, 'Endpoint')).fill('http://echo-mcp:8090')
  await select(create, '凭证', 'Echo Credential Renamed')
  await select(create, '所属部门', company)
  await (await field(create, 'Deployment 名称')).fill('Echo Model Deployment')
  await (await field(create, '模型名称')).fill('echo-model-v1')
  await (await field(create, 'Alias')).fill('echo-chat')
  await expect(create.getByRole('button', { name: '保存', exact: true })).toBeInViewport()
  await submit(create, '保存')
  await expect(page.getByRole('row', { name: /echo-chat/ }).getByText('未测试', { exact: true })).toBeVisible()
  await page.getByRole('row', { name: /echo-chat/ }).getByRole('link', { name: '详情' }).click()
  await expect(page.getByText('未测试', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '编辑模型' }).click()
  const edit = await dialog(page, '编辑模型')
  await expect(edit.getByRole('button', { name: '保存', exact: true })).toBeInViewport()
  await (await field(edit, '模型名称')).fill('echo-model-v2')
  await (await field(edit, '默认参数 JSON')).fill('{"temperature":0.1}')
  await (await field(edit, '输入单价/百万 Token')).fill('1.25')
  await (await field(edit, '输出单价/百万 Token')).fill('2.50')
  await submit(edit, '保存')
  await expect(page.getByText('r2', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('echo-model-v2', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('未测试', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Invalid Date', { exact: true })).toHaveCount(0)
}

async function createAndExerciseMcp(page: Page) {
  await page.getByRole('link', { name: 'MCP 服务', exact: true }).click()
  await page.getByRole('button', { name: '接入 MCP Server' }).click()
  const create = await dialog(page, '接入 MCP Server')
  await (await field(create, '名称')).fill('Echo MCP')
  await (await field(create, 'Endpoint')).fill('http://echo-mcp:8090/mcp')
  await select(create, '凭证', 'Echo Credential Renamed')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Echo MCP/ }).getByRole('link', { name: '详情' }).click()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '发现工具' }).click()
  await expect(page.getByRole('button', { name: /echo · v1/ })).toBeVisible()
  await expect(page.getByText('text', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('string', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('必填', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('main').getByText('资源授权', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Invalid Date', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: '工具策略' }).click()
  const policy = await dialog(page, '工具策略')
  await select(policy, '副作用等级', '无副作用')
  await submit(policy, '保存')
  await page.getByRole('button', { name: '调试调用' }).click()
  const debug = await dialog(page, '调试调用')
  await (await field(debug, '调用参数 JSON')).fill('{"text":"Agentx E2E"}')
  await submit(debug, '确认调用')
  await expect(page.locator('pre').filter({ hasText: 'Agentx E2E' })).toBeVisible()

  await page.goto('/mcp')
  await page.getByRole('button', { name: '接入 MCP Server' }).click()
  const blocked = await dialog(page, '接入 MCP Server')
  await (await field(blocked, '名称')).fill('Blocked Metadata MCP')
  await (await field(blocked, 'Endpoint')).fill('http://169.254.169.254/latest/meta-data')
  await select(blocked, '所属部门', company)
  await blocked.getByRole('button', { name: '保存', exact: true }).click()
  await expect(blocked.getByText(/blocked network|not allowed|不允许|FORBIDDEN/i)).toBeVisible()
  await blocked.getByRole('button', { name: '取消' }).click()

  await page.getByRole('button', { name: '接入 MCP Server' }).click()
  const unavailable = await dialog(page, '接入 MCP Server')
  await (await field(unavailable, '名称')).fill('Unavailable MCP')
  await (await field(unavailable, 'Endpoint')).fill('http://echo-mcp:65530/mcp')
  await select(unavailable, '所属部门', company)
  await submit(unavailable, '保存')
  await page.getByRole('row', { name: /Unavailable MCP/ }).getByRole('link', { name: '详情' }).click()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText(/could not be reached|无法连接|MCP_CONNECTION_FAILED|request timed out/i).first()).toBeVisible()
}

async function createSkillWorkspace(page: Page) {
  await page.getByRole('link', { name: 'Skills', exact: true }).click()
  await page.getByRole('button', { name: '新建 Skill' }).click()
  const create = await dialog(page, '新建 Skill')
  await (await field(create, '名称')).fill('Workspace Skill')
  await (await field(create, '描述')).fill('Managed entirely in the browser')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Workspace Skill/ }).getByRole('link', { name: '详情' }).click()

  const skillDescription = page.getByLabel('Skill 描述')
  await expect(skillDescription).toHaveValue('Managed entirely in the browser')
  await skillDescription.fill('Build browser-managed reusable instructions')
  await page.getByRole('button', { name: '保存', exact: true }).last().click()
  await expect(page.getByText('Build browser-managed reusable instructions', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: '新建目录' }).click()
  const folder = await dialog(page, '新建目录')
  await (await field(folder, '目录名称')).fill('docs')
  await submit(folder, '保存')
  await page.getByRole('button', { name: '新建 Markdown' }).click()
  const markdown = await dialog(page, '新建 Markdown')
  await (await field(markdown, 'Markdown 文件名')).fill('guide.md')
  await select(markdown, '父目录', 'docs')
  await submit(markdown, '保存')

  await page.getByRole('button', { name: 'docs' }).click()
  const upload = page.locator('input[type=file]').nth(1)
  await upload.setInputFiles({ name: 'sample.txt', mimeType: 'text/plain', buffer: Buffer.from('Agentx Skill attachment') })
  await expect(page.getByRole('button', { name: 'sample.txt' })).toBeVisible()
  await expect(page.getByText('文件已上传', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'guide.md' }).click()
  const richEditor = page.locator('.agentx-markdown-editor')
  const editor = richEditor.locator('[contenteditable="true"]').first()
  await editor.click()
  await expect(richEditor.getByRole('radio', { name: '加粗' })).toBeVisible()
  await richEditor.getByRole('radio', { name: '加粗' }).click()
  await page.keyboard.type('Guide')
  await richEditor.getByRole('radio', { name: '取消加粗' }).click()
  await page.keyboard.press('Enter')
  await richEditor.getByRole('radio', { name: '无序列表' }).click()
  await page.keyboard.type('Use the attached file')
  await page.getByRole('button', { name: '插入引用' }).click()
  const reference = await dialog(page, '插入引用')
  await select(reference, '引用目标', 'docs/sample.txt')
  await submit(reference, '插入引用')
  await page.getByRole('button', { name: '保存', exact: true }).last().click()

  await page.getByRole('button', { name: '新建 Markdown' }).click()
  const temporary = await dialog(page, '新建 Markdown')
  await (await field(temporary, 'Markdown 文件名')).fill('temporary.md')
  await submit(temporary, '保存')
  await page.getByRole('button', { name: 'temporary.md' }).click()
  await page.getByRole('button', { name: '删除条目' }).click()
  const remove = await dialog(page, '删除条目')
  await remove.getByRole('button', { name: '取消' }).click()
  await expect(remove).toBeHidden()
  await page.getByRole('button', { name: '删除条目' }).click()
  const confirm = await dialog(page, '删除条目')
  await confirm.getByRole('button', { name: '删除条目' }).click()
  await expect(confirm).toBeHidden()
  await expect(page.getByRole('button', { name: 'temporary.md' })).toHaveCount(0)

  await page.getByRole('button', { name: '发布工作区版本' }).click()
  const publish = await dialog(page, '发布工作区版本')
  await submit(publish, '发布')
  await expect(page.getByText('v1', { exact: true })).toBeVisible()
}

async function configureCentralResourceGrants(page: Page) {
  await page.getByRole('link', { name: '资源授权', exact: true }).click()
  await expect(page.getByRole('heading', { name: '资源授权' })).toBeVisible()
  const resourceTabs = page.getByRole('tablist', { name: '资源类型' })
  await expect(resourceTabs.getByRole('tab')).toHaveCount(9)
  await expect(resourceTabs.getByRole('tab', { name: '沙箱配置', exact: true })).toBeVisible()
  await resourceTabs.getByRole('tab', { name: '模型', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'echo-chat' })).toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: 'Echo Credential Renamed' })).toHaveCount(0)
  await grantResource(page, 'Echo Credential Renamed', '凭证', 'workflow')
  await grantResource(page, 'echo-chat', '模型', 'workflow')
  await grantResource(page, 'echo', 'MCP Tool', 'workflow')
  await grantResource(page, 'Workspace Skill', 'Skill', 'workflow')
  await grantResource(page, 'echo-chat', '模型', 'department', '查看')

  await resourceTabs.getByRole('tab', { name: 'Skill', exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: 'Workspace Skill' }).filter({ hasText: 'Skill' }).first()
  await row.getByRole('button', { name: '管理授权' }).click()
  const grant = page.getByRole('dialog', { name: /管理.*Workspace Skill.*授权/ })
  await grant.getByLabel('撤销授权').click()
  const confirmation = page.getByRole('dialog', { name: '确认撤销授权' })
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole('button', { name: '取消' }).click()
  await expect(confirmation).toBeHidden()
  await grant.getByLabel('撤销授权').click()
  await page.getByRole('dialog', { name: '确认撤销授权' }).getByRole('button', { name: '确认撤销' }).click()
  await expect(grant.getByText('MCP Echo Workflow', { exact: true })).toHaveCount(0)
  await grant.getByRole('button', { name: '取消' }).click()
  await grantResource(page, 'Workspace Skill', 'Skill', 'workflow')
}

async function configureAndPublishWorkflow(page: Page) {
  await page.getByRole('link', { name: /^工作流/ }).click()
  await page.getByRole('row', { name: /MCP Echo Workflow/ }).getByRole('link', { name: '打开画布' }).click()
  await expect(page.getByTestId('workflow-canvas')).toBeVisible()
  await page.getByTestId('palette-action-mcp_tool').click()
  const toolNode = page.locator('.react-flow__node-manifest').filter({ hasText: /mcp tool/i }).first()
  await expect(toolNode).toBeVisible()
  const resource = page.getByTestId('resource-selector-mcp_tool').getByRole('combobox')
  await resource.click()
  await page.getByRole('option', { name: /echo/ }).click()
  await fillMonaco(page, page.getByTestId('parameter-arguments'), '{"text":"Agentx E2E"}')
  const source = page.locator('.react-flow__node').filter({ hasText: 'Manual Trigger' }).first().locator('.react-flow__handle.source[data-handleid="main"]')
  const target = toolNode.locator('.react-flow__handle.target[data-handleid="main"]')
  await expect(source).toBeVisible()
  await expect(target).toBeVisible()
  const sourceBox = await source.boundingBox()
  const targetBox = await target.boundingBox()
  if (!sourceBox || !targetBox) throw new Error('Workflow node handles are not visible')
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(targetBox.x + targetBox.width / 2, targetBox.y + targetBox.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(page.locator('.react-flow__edge')).toHaveCount(1)
  const save = page.getByRole('button', { name: '保存', exact: true })
  const draftRequest = page.waitForRequest((request) => request.method() === 'PUT' && /\/workflows\/[^/]+\/draft$/.test(request.url()))
  await save.click()
  const payload = (await draftRequest).postDataJSON() as { definition: { nodes: Array<{ type: string; parameters: Record<string, unknown> }> } }
  expect(payload.definition.nodes.find((node) => node.type === 'mcp_tool')?.parameters).toEqual({ arguments: { text: 'Agentx E2E' } })
  await expect(page.getByRole('status').filter({ hasText: /mcp_server .* requires use grant/i })).toBeVisible()

  const grantsPage = await page.context().newPage()
  await grantsPage.goto('/resource-grants')
  await expect(grantsPage.getByRole('heading', { name: '资源授权' })).toBeVisible()
  await grantResource(grantsPage, 'Echo MCP', 'MCP Server', 'workflow')
  await grantsPage.close()

  await save.click()
  await expect(page.locator('header').getByText(/Revision \d+ · 已保存/)).toBeVisible({ timeout: 30_000 })
  await page.getByRole('link', { name: '返回', exact: true }).click()
  await expect(page.getByText('资源与授权校验通过')).toBeVisible()
  await page.getByRole('button', { name: '创建版本' }).click()
  await expect(page.getByText('v1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '发布', exact: true }).first().click()
  const publish = await dialog(page, '发布')
  await select(publish, '选择环境', 'Development')
  await select(publish, '选择版本', 'v1')
  await submit(publish, '发布')
  await expect(page.getByText(/Development · v1/)).toBeVisible()
}

async function verifyThemeLocaleAndRbac(page: Page, browser: Browser) {
  await page.getByRole('button', { name: '主题' }).click()
  await page.getByRole('menuitemradio', { name: '深色' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.getByRole('button', { name: '语言' }).click()
  await page.getByRole('menuitemradio', { name: 'English' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await page.getByRole('button', { name: 'Language' }).click()
  await page.getByRole('menuitemradio', { name: '简体中文' }).click()

  await page.getByRole('link', { name: '部门与用户' }).click()
  await page.getByRole('button', { name: '创建用户' }).click()
  const user = await dialog(page, '创建用户')
  await (await field(user, '用户名')).fill('e2e.member')
  await (await field(user, '用户名称')).fill('E2E Member')
  await submit(user, '保存')

  const memberContext = await browser.newContext({ baseURL: page.url().split('/').slice(0, 3).join('/') })
  const member = await memberContext.newPage()
  await member.goto('/login')
  await member.getByLabel('用户名').fill('e2e.member')
  await member.getByLabel('密码').fill('123456')
  await member.getByRole('button', { name: '登录' }).click()
  await member.getByLabel('新密码', { exact: true }).fill('agentx-e2e-member-password')
  await member.getByLabel('确认新密码', { exact: true }).fill('agentx-e2e-member-password')
  await member.getByRole('button', { name: '更新密码并登录' }).click()
  await expect(member).toHaveURL(/\/$/)
  await member.goto('/mcp')
  await expect(member).toHaveURL(/\/403$/)
  await expect(member.getByRole('heading', { name: '无权访问' })).toBeVisible()
  await memberContext.close()
}

test('M2.1 control plane works through real UI actions', async ({ browser, page }) => {
  await bootstrap(page)
  await createWorkflow(page)
  await createCredentialAndVerifyConflict(page)
  await createAndReviseModel(page)
  await createAndExerciseMcp(page)
  await createSkillWorkspace(page)
  await configureCentralResourceGrants(page)
  await configureAndPublishWorkflow(page)
  await verifyThemeLocaleAndRbac(page, browser)
})
