import { expect, type Browser, type Locator, type Page, test } from '@playwright/test'

const company = 'Agentx E2E'
const adminPassword = 'agentx-e2e-admin-password'
const echoBaseUrl = process.env.AGENTX_E2E_ECHO_BASE_URL ?? 'http://echo-mcp:8090'
const lightRagBaseUrl = process.env.AGENTX_E2E_LIGHTRAG_BASE_URL ?? 'http://lightrag:9621'
const mem0BaseUrl = process.env.AGENTX_E2E_MEM0_BASE_URL ?? 'http://mem0:8000'

async function dialog(page: Page, title: string) {
  const value = page.getByRole('dialog', { name: title })
  await expect(value).toBeVisible()
  return value
}

async function field(container: Locator, label: string) {
  return container.locator('label').filter({ hasText: label }).locator('input, textarea').first()
}

async function select(container: Locator, label: string, option: string) {
  await container.getByRole('combobox', { name: label, exact: true }).click()
  await container.page().getByRole('option', { name: option, exact: true }).click()
}

async function submit(container: Locator, name: string) {
  await container.getByRole('button', { name, exact: true }).click()
  await expect(container).toBeHidden()
}

async function loginIfNeeded(page: Page) {
  const login = page.getByRole('button', { name: /^(登录|Sign in|Login)$/ })
  await Promise.race([
    page.locator('nav').waitFor({ state: 'visible' }),
    login.waitFor({ state: 'visible' }),
  ])
  if (!(await login.isVisible())) return
  await page.getByLabel(/用户名|Username/).fill('admin')
  await page.getByLabel(/密码|Password/).fill(adminPassword)
  await login.click()
  await expect(page).toHaveURL(/\/$/)
}

async function connectHandles(page: Page, source: Locator, target: Locator) {
  const sourceBox = await source.boundingBox()
  const targetBox = await target.boundingBox()
  if (!sourceBox || !targetBox) throw new Error('Workflow node handles are not visible')
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(targetBox.x + targetBox.width / 2, targetBox.y + targetBox.height / 2, { steps: 12 })
  await page.mouse.up()
}

async function selectedNode(page: Page) {
  const selected = page.locator('.react-flow__node.selected').first()
  await expect(selected).toBeVisible()
  const nodeId = await selected.getAttribute('data-id')
  if (!nodeId) throw new Error('Selected workflow node does not expose a data-id')
  return page.locator(`.react-flow__node[data-id="${nodeId}"]`)
}

async function grantResource(page: Page, name: string, resourceType: string, subject: 'workflow' | 'department', operation = '使用') {
  await page.getByRole('tab', { name: resourceType, exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: name }).filter({ hasText: resourceType }).first()
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '管理授权' }).click()
  const grant = page.getByRole('dialog', { name: new RegExp(`管理.*${name}.*授权`) })
  await expect(grant).toBeVisible()
  if (subject === 'department') {
    await select(grant, '授权对象类型', '部门')
    await select(grant, '授权对象', company)
  } else {
    await select(grant, '授权对象类型', '工作流运行身份')
    await select(grant, '授权对象', 'MCP Echo Workflow')
  }
  await select(grant, '操作', operation)
  await grant.getByRole('button', { name: '添加授权' }).click()
  await expect(grant.getByRole('button', { name: '撤销授权' })).toHaveCount(1)
  await grant.getByRole('button', { name: '取消' }).click()
  await expect(grant).toBeHidden()
}

async function bootstrap(page: Page) {
  await page.goto('/')
  const setup = page.getByRole('button', { name: '初始化并进入工作台' })
  await Promise.race([
    setup.waitFor({ state: 'visible' }),
    page.getByRole('button', { name: /^(登录|Sign in|Login)$/ }).waitFor({ state: 'visible' }),
    page.locator('nav').waitFor({ state: 'visible' }),
  ])
  if (await setup.isVisible()) {
    await page.getByLabel('公司名称').fill(company)
    await page.getByLabel('用户名').fill('admin')
    await page.getByLabel('管理员姓名').fill('E2E Admin')
    await page.getByLabel('密码').fill(adminPassword)
    await setup.click()
    await expect(page).toHaveURL(/\/$/)
  } else {
    await loginIfNeeded(page)
  }
  await expect(page.getByRole('main').getByText(new RegExp(company))).toBeVisible()
}

async function createWorkflow(page: Page) {
  await page.getByRole('link', { name: /^工作流/ }).click()
  await page.getByRole('button', { name: '新建工作流' }).click()
  const form = await dialog(page, '新建工作流')
  await (await field(form, '工作流名称')).fill('MCP Echo Workflow')
  await (await field(form, '描述')).fill('M2.1 browser acceptance workflow')
  await submit(form, '保存')
  await expect(page.getByRole('heading', { name: 'MCP Echo Workflow' })).toBeVisible()
}

async function createCredentialAndVerifyConflict(page: Page) {
  await page.getByRole('link', { name: '凭证', exact: true }).click()
  await page.getByRole('button', { name: '新建凭证' }).click()
  const create = await dialog(page, '新建凭证')
  await (await field(create, '名称')).fill('Echo Credential')
  await select(create, '凭证类型', 'Bearer Token')
  await (await field(create, '密钥内容')).fill('m5-model-secret')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Echo Credential/ }).getByRole('link', { name: '详情' }).click()

  const second = await page.context().newPage()
  await second.goto(page.url())
  await expect(second.getByRole('heading', { name: 'Echo Credential' })).toBeVisible()

  await page.getByRole('button', { name: '编辑', exact: true }).click()
  const rename = await dialog(page, '修改凭证名称')
  await (await field(rename, '名称')).fill('Echo Credential Renamed')
  await submit(rename, '保存')
  await expect(page.getByRole('heading', { name: 'Echo Credential Renamed' })).toBeVisible()

  await second.getByRole('button', { name: '编辑', exact: true }).click()
  const stale = await dialog(second, '修改凭证名称')
  await (await field(stale, '名称')).fill('Stale Rename')
  await stale.getByRole('button', { name: '保存', exact: true }).click()
  await expect(stale.getByText(/Credential changed|凭证已被修改|CONFLICT/i)).toBeVisible()
  await second.close()
  await page.goto('/credentials')
}

async function createAndReviseModel(page: Page) {
  await page.getByRole('link', { name: '模型服务', exact: true }).click()
  await page.getByRole('button', { name: '新建模型' }).click()
  const create = await dialog(page, '新建模型')
  await expect(create.locator('label').filter({ hasText: '连接名称' }).getByText('*', { exact: true })).toBeVisible()
  await expect(create.locator('label').filter({ hasText: 'API 格式' }).getByText('*', { exact: true })).toBeVisible()
  await expect(create.locator('label').filter({ hasText: '所属部门' }).getByText('*', { exact: true })).toBeVisible()
  await create.getByRole('button', { name: '保存', exact: true }).click()
  await expect(create.getByText('此项为必填项', { exact: true }).first()).toBeVisible()
  await expect(await field(create, '连接名称')).toBeFocused()
  await expect(await field(create, '连接名称')).toHaveAttribute('aria-invalid', 'true')
  await expect(create.getByText('Unprocessable Entity', { exact: true })).toHaveCount(0)
  await (await field(create, '连接名称')).fill('E2E Model Connection')
  await (await field(create, 'Endpoint')).fill(`${echoBaseUrl}/v1`)
  await select(create, '凭证', 'Echo Credential Renamed')
  await (await field(create, '模型名称')).fill('echo-chat')
  await (await field(create, '上游模型 ID')).fill('echo-model-v1')
  await (await field(create, '输入单价/百万 Token')).fill('0.50')
  await (await field(create, '输出单价/百万 Token')).fill('0.80')
  await select(create, '所属部门', company)
  await expect(create.getByRole('button', { name: '保存', exact: true })).toBeInViewport()
  await submit(create, '保存')
  await page.getByRole('button', { name: '新建模型' }).click()
  const duplicate = await dialog(page, '新建模型')
  await (await field(duplicate, '连接名称')).fill('Duplicate Model Connection')
  await (await field(duplicate, 'Endpoint')).fill(`${echoBaseUrl}/v1`)
  await select(duplicate, '凭证', 'Echo Credential Renamed')
  await (await field(duplicate, '模型名称')).fill('echo-chat')
  await (await field(duplicate, '上游模型 ID')).fill('echo-model-v1')
  await select(duplicate, '所属部门', company)
  await duplicate.getByRole('button', { name: '保存', exact: true }).click()
  await expect(duplicate.getByText('该模型名称已存在。')).toBeVisible()
  await expect(await field(duplicate, '模型名称')).toHaveAttribute('aria-invalid', 'true')
  await duplicate.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('row', { name: /echo-chat/ }).getByText(/未测试|未知（untested）/)).toBeVisible()
  await page.getByRole('row', { name: /echo-chat/ }).getByRole('link', { name: '详情' }).click()
  await expect(page.getByText(/未测试|未知（untested）/).first()).toBeVisible()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '编辑模型' }).click()
  const edit = await dialog(page, '编辑模型')
  await expect(edit.getByRole('button', { name: '保存', exact: true })).toBeInViewport()
  await expect(edit.getByRole('combobox', { name: 'API 格式', exact: true })).toHaveText('OpenAI Chat Completions')
  await expect(await field(edit, '输入单价/百万 Token')).toHaveValue('0.50000000')
  await expect(await field(edit, '输出单价/百万 Token')).toHaveValue('0.80000000')
  await (await field(edit, '连接名称')).fill('E2E Model Connection v2')
  await (await field(edit, '上游模型 ID')).fill('echo-model-v2')
  await (await field(edit, '默认参数 JSON')).fill('{"temperature":0.1}')
  await (await field(edit, '输入单价/百万 Token')).fill('1.25')
  await (await field(edit, '输出单价/百万 Token')).fill('2.50')
  await submit(edit, '保存')
  await expect(page.getByText('r2', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('echo-model-v2', { exact: true }).first()).toBeVisible()
  await expect(page.getByText(/未测试|未知（untested）/).first()).toBeVisible()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '编辑模型' }).click()
  const saved = await dialog(page, '编辑模型')
  await expect(await field(saved, '输入单价/百万 Token')).toHaveValue('1.25000000')
  await expect(await field(saved, '输出单价/百万 Token')).toHaveValue('2.50000000')
  await saved.getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByText('Invalid Date', { exact: true })).toHaveCount(0)
}

async function createAndExerciseMcp(page: Page) {
  await page.getByRole('link', { name: 'MCP 服务', exact: true }).click()
  await page.getByRole('button', { name: '接入 MCP 服务' }).click()
  const create = await dialog(page, '接入 MCP 服务')
  await (await field(create, '名称')).fill('Echo MCP')
  await (await field(create, 'Endpoint')).fill(`${echoBaseUrl}/mcp`)
  await select(create, '凭证', 'Echo Credential Renamed')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Echo MCP/ }).getByRole('link', { name: '详情' }).click()
  await page.getByRole('button', { name: '测试连接' }).click()
  await expect(page.getByText('连接正常', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '发现工具' }).click()
  await expect(page.getByRole('button', { name: /echo · v1/ })).toBeVisible()
  await expect(page.getByText('text', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('string', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('必填', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('main').getByText('资源授权', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Invalid Date', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: '工具策略' }).click()
  const policy = await dialog(page, '工具策略')
  await select(policy, '副作用等级', '无副作用')
  await submit(policy, '保存')
  await page.getByRole('button', { name: '调试调用' }).click()
  const debug = await dialog(page, '调试调用')
  await (await field(debug, '调用参数 JSON')).fill('{"text":"Agentx E2E"}')
  await submit(debug, '确认调用')
  await expect(page.locator('pre').filter({ hasText: 'Agentx E2E' })).toBeVisible()

  await page.goto('/mcp')
  await page.getByRole('button', { name: '接入 MCP 服务' }).click()
  const blocked = await dialog(page, '接入 MCP 服务')
  await (await field(blocked, '名称')).fill('Blocked Metadata MCP')
  await (await field(blocked, 'Endpoint')).fill('http://169.254.169.254/latest/meta-data')
  await select(blocked, '所属部门', company)
  await blocked.getByRole('button', { name: '保存', exact: true }).click()
  await expect(blocked.getByText(/blocked network|not allowed|不允许|没有执行此操作的权限|FORBIDDEN/i)).toBeVisible()
  await blocked.getByRole('button', { name: '取消' }).click()

  await page.getByRole('button', { name: '接入 MCP 服务' }).click()
  const unavailable = await dialog(page, '接入 MCP 服务')
  await (await field(unavailable, '名称')).fill('Unavailable MCP')
  await (await field(unavailable, 'Endpoint')).fill(`${new URL(echoBaseUrl).protocol}//${new URL(echoBaseUrl).hostname}:65530/mcp`)
  await select(unavailable, '所属部门', company)
  await unavailable.getByRole('button', { name: '保存', exact: true }).click()
  await expect(unavailable).toBeHidden()
  await page.getByRole('row', { name: /Unavailable MCP/ }).getByRole('link', { name: '详情' }).click()
  const connectionCheck = page.waitForResponse(
    (response) => response.request().method() === 'POST' && new URL(response.url()).pathname.endsWith('/test-connection'),
    { timeout: 25_000 },
  )
  await page.getByRole('button', { name: '测试连接' }).click()
  expect((await connectionCheck).status()).toBe(200)
  await expect(page.getByText(/could not be reached|无法连接|MCP_CONNECTION_FAILED|request timed out/i).first()).toBeVisible({ timeout: 5_000 })
}

async function createSkillWorkspace(page: Page) {
  await page.getByRole('link', { name: '技能', exact: true }).click()
  await page.getByRole('button', { name: '新建技能' }).click()
  const create = await dialog(page, '新建技能')
  await (await field(create, '名称')).fill('Workspace Skill')
  await (await field(create, '技能别名')).fill('workspace-skill')
  await (await field(create, '技能描述')).fill('Managed entirely in the browser')
  await select(create, '所属部门', company)
  await submit(create, '保存')
  await page.getByRole('row', { name: /Workspace Skill/ }).getByRole('link', { name: '详情' }).click()

  const skillDescription = page.getByLabel('技能描述')
  await expect(skillDescription).toHaveValue('Managed entirely in the browser')
  await skillDescription.fill('Build browser-managed reusable instructions')
  await page.getByRole('button', { name: '保存', exact: true }).last().click()
  await expect(page.getByText('Build browser-managed reusable instructions', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: '编辑' }).click()
  const edit = await dialog(page, '编辑技能')
  await (await field(edit, '技能别名')).fill('workspace-skill-updated')
  await submit(edit, '保存')
  await expect(page.getByText('技能别名: workspace-skill-updated', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: '新建目录' }).click()
  const folder = await dialog(page, '新建目录')
  await (await field(folder, '目录名称')).fill('docs')
  await submit(folder, '保存')
  await page.getByRole('button', { name: '新建 Markdown' }).click()
  const markdown = await dialog(page, '新建 Markdown')
  await (await field(markdown, 'Markdown 文件名')).fill('guide.md')
  await select(markdown, '父目录', 'docs')
  await submit(markdown, '保存')

  await page.getByRole('button', { name: 'docs' }).click()
  const upload = page.locator('input[type=file]').nth(1)
  await upload.setInputFiles({ name: 'sample.txt', mimeType: 'text/plain', buffer: Buffer.from('Agentx Skill attachment') })
  await expect(page.getByRole('button', { name: 'sample.txt' })).toBeVisible()
  await expect(page.getByText('文件已上传', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'guide.md' }).click()
  const richEditor = page.locator('.agentx-markdown-editor')
  const editor = richEditor.locator('[contenteditable="true"]').first()
  await editor.click()
  const bold = richEditor.getByRole('radio', { name: /^(Bold|加粗)$/ })
  await expect(bold).toBeVisible()
  await bold.click()
  await page.keyboard.type('Guide')
  await richEditor.getByRole('radio', { name: /^(Remove bold|取消加粗)$/ }).click()
  await page.keyboard.press('Enter')
  await richEditor.getByRole('radio', { name: /^(Bulleted list|无序列表)$/ }).click()
  await page.keyboard.type('Use the attached file')
  await page.getByRole('button', { name: '插入引用' }).click()
  const reference = await dialog(page, '插入引用')
  await select(reference, '引用目标', 'docs/sample.txt')
  await submit(reference, '插入引用')
  await page.getByRole('button', { name: '保存', exact: true }).last().click()

  await page.getByRole('button', { name: '发布工作区版本' }).click()
  const publish = await dialog(page, '发布工作区版本')
  await submit(publish, '发布')
  await expect(page.getByText('v1', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: '启用', exact: true }).click()
  await expect(page.getByRole('button', { name: '停用', exact: true })).toBeVisible()
}

async function configureCentralResourceGrants(page: Page) {
  await page.getByRole('link', { name: '资源授权', exact: true }).click()
  await expect(page.getByRole('heading', { name: '资源授权' })).toBeVisible()
  const resourceTabs = page.getByRole('tablist', { name: '资源类型' })
  await expect(resourceTabs.getByRole('tab')).toHaveCount(9)
  await expect(resourceTabs.getByRole('tab', { name: '沙箱配置', exact: true })).toBeVisible()
  await resourceTabs.getByRole('tab', { name: '模型', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: 'echo-chat' })).toBeVisible()
  await expect(page.getByRole('row').filter({ hasText: 'Echo Credential Renamed' })).toHaveCount(0)
  await grantResource(page, 'Echo Credential Renamed', '凭证', 'workflow')
  await grantResource(page, 'echo-chat', '模型', 'workflow')
  await grantResource(page, 'Echo MCP', 'MCP 服务', 'workflow')
  await grantResource(page, 'echo', 'MCP 工具', 'workflow')
  await grantResource(page, 'Workspace Skill', '技能', 'workflow')
  await grantResource(page, 'echo-chat', '模型', 'department', '查看')

  await resourceTabs.getByRole('tab', { name: '技能', exact: true }).click()
  const row = page.getByRole('row').filter({ hasText: 'Workspace Skill' }).filter({ hasText: '技能' }).first()
  await row.getByRole('button', { name: '管理授权' }).click()
  const grant = page.getByRole('dialog', { name: /管理.*Workspace Skill.*授权/ })
  await grant.getByLabel('撤销授权').click()
  const confirmation = page.getByRole('dialog', { name: '确认撤销授权' })
  await expect(confirmation).toBeVisible()
  await confirmation.getByRole('button', { name: '取消' }).click()
  await expect(confirmation).toBeHidden()
  await grant.getByLabel('撤销授权').click()
  await page.getByRole('dialog', { name: '确认撤销授权' }).getByRole('button', { name: '确认撤销' }).click()
  await expect(grant.getByText('MCP Echo Workflow', { exact: true })).toHaveCount(0)
  await grant.getByRole('button', { name: '取消' }).click()
  await grantResource(page, 'Workspace Skill', '技能', 'workflow')
}

async function configureAndPublishWorkflow(page: Page) {
  await page.getByRole('link', { name: /^工作流/ }).click()
  await page.getByRole('row', { name: /MCP Echo Workflow/ }).getByRole('link', { name: '打开画布' }).click()
  await expect(page.getByTestId('workflow-canvas')).toBeVisible()
  await page.getByTestId('node-creator-trigger').click()
  await expect(page.getByTestId('node-creator')).toBeVisible()
  await page.getByRole('textbox', { name: '搜索节点' }).fill('智能体')
  await page.getByTestId('palette-action-agent').click()
  const agentNode = await selectedNode(page)
  await expect(page.getByTestId('node-details-view')).toBeVisible()
  await page.getByTestId('parameter-systemPrompt').getByRole('textbox').fill('Use the attached MCP tool to answer the question.')
  await page.getByTestId('node-details-view').getByRole('button', { name: /关闭|Close/ }).click()

  await page.getByTestId('node-creator-trigger').click()
  await page.getByTestId('palette-group-attachments').click()
  await page.getByTestId('palette-binding-model').click()
  const modelNode = await selectedNode(page)
  await page.getByTestId('attachment-resource').getByRole('combobox').click()
  await page.getByRole('option', { name: /echo-chat/ }).click()
  await page.getByTestId('node-details-view').getByRole('button', { name: /关闭|Close/ }).click()

  await page.getByTestId('node-creator-trigger').click()
  await page.getByTestId('palette-group-attachments').click()
  await page.getByTestId('palette-binding-mcp_tool').click()
  const toolNode = await selectedNode(page)
  await page.getByTestId('attachment-resource').getByRole('combobox').click()
  await page.getByRole('option', { name: /echo/ }).click()
  await page.getByTestId('node-details-view').getByRole('button', { name: /关闭|Close/ }).click()

  await page.getByRole('button', { name: /^(适应画布|Fit View)$/ }).click()
  await connectHandles(page, page.getByTestId('workflow-start').locator('.react-flow__handle.source[data-handleid="main"]'), agentNode.locator('.react-flow__handle.target[data-handleid="main"]'))
  await connectHandles(page, agentNode.locator('.react-flow__handle.source[data-handleid="main"]'), page.getByTestId('workflow-end').locator('.react-flow__handle.target[data-handleid="main"]'))
  await connectHandles(page, modelNode.locator('.react-flow__handle.source[data-handleid="resource"]'), agentNode.locator('.react-flow__handle.target[data-handleid="binding:ai_model"]'))
  await connectHandles(page, toolNode.locator('.react-flow__handle.source[data-handleid="resource"]'), agentNode.locator('.react-flow__handle.target[data-handleid="binding:ai_tool"]'))
  await expect(page.locator('.react-flow__edge')).toHaveCount(4)
  await page.getByTestId('workflow-start').click()
  const startPanel = page.getByTestId('workflow-interface-panel')
  await expect(startPanel).toBeVisible()
  await startPanel.getByRole('button', { name: /添加字段|Add field/ }).first().click()
  let inputDialog = page.getByRole('dialog', { name: /添加字段|Add field/ })
  const questionName = inputDialog.getByLabel(/字段名|Field name/)
  await questionName.fill('question')
  await questionName.blur()
  await inputDialog.getByLabel(/标题|Title/).fill('Question')
  await inputDialog.getByLabel(/必填|Required/).check()
  await inputDialog.getByRole('button', { name: /保存|Save/ }).click()
  await startPanel.getByRole('button', { name: /添加字段|Add field/ }).first().click()
  inputDialog = page.getByRole('dialog', { name: /添加字段|Add field/ })
  const attachmentsName = inputDialog.getByLabel(/字段名|Field name/)
  await attachmentsName.fill('attachments')
  await attachmentsName.blur()
  await inputDialog.getByLabel(/类型|Type/).click()
  await page.getByRole('option', { name: /文件数组|File array/ }).click()
  await inputDialog.getByLabel(/标题|Title/).fill('Attachments')
  await inputDialog.getByLabel(/允许的文件类型|Allowed content types/).fill('application/pdf, image/*')
  await inputDialog.getByLabel(/最大文件大小|Maximum file size/).fill('1048576')
  await inputDialog.getByLabel(/最少文件数|Minimum files/).fill('0')
  await inputDialog.getByLabel(/最多文件数|Maximum files/).fill('3')
  await inputDialog.getByLabel(/文件总大小上限|Maximum total file size/).fill('2097152')
  await inputDialog.getByRole('button', { name: /保存|Save/ }).click()
  await startPanel.getByRole('button', { name: /关闭|Close/ }).click()
  await agentNode.dispatchEvent('click')
  const questionEditor = page.getByTestId('parameter-userQuestion').getByRole('textbox', { name: 'Value' })
  await questionEditor.click()
  let picker = page.getByTestId('reference-picker')
  await picker.getByRole('button', { name: /输入|Inputs/ }).click()
  await picker.getByRole('button', { name: /question/i }).click()
  await expect(page.getByTestId('parameter-userQuestion').locator('[data-agentx-variable]')).toBeVisible()
  await page.getByTestId('node-details-view').getByRole('button', { name: /关闭|Close/ }).click()
  await page.getByTestId('workflow-end').click()
  const endPanel = page.getByTestId('workflow-interface-panel')
  await expect(endPanel).toBeVisible()
  await endPanel.getByRole('button', { name: /添加字段|Add field/ }).first().click()
  const outputDialog = page.getByRole('dialog', { name: /输出字段|Output field/ })
  await outputDialog.getByLabel(/输出名称|Output name/).fill('answer')
  await outputDialog.getByRole('textbox', { name: 'Value' }).click()
  picker = page.getByTestId('reference-picker')
  await picker.getByRole('button', { name: /输出|Outputs/ }).click()
  for (const label of ['agent', 'main', 'current', 'text']) await picker.getByRole('button', { name: new RegExp(label, 'i') }).first().click()
  await expect(outputDialog.locator('[data-agentx-variable]')).toBeVisible()
  await outputDialog.getByLabel(/必填|Required/).check()
  await outputDialog.getByRole('button', { name: /保存|Save/ }).click()
  await endPanel.getByRole('button', { name: /关闭|Close/ }).click()
  const save = page.getByRole('button', { name: '保存', exact: true })
  const draftRequest = page.waitForRequest((request) => request.method() === 'PUT' && /\/workflows\/[^/]+\/draft$/.test(request.url()))
  const savedResponsePromise = page.waitForResponse((response) => response.request().method() === 'PUT' && /\/workflows\/[^/]+\/draft$/.test(response.url()))
  await save.click()
  const payload = (await draftRequest).postDataJSON() as { definition: { nodes: Array<{ type: string; parameters: Record<string, unknown>; resourceReferences: Array<{ bindingRole?: string }> }>; end: { outputs: Record<string, { value: { kind: string; selector?: { namespace: string; port?: string; path: string[] } } }> } } }
  const agent = payload.definition.nodes.find((node) => node.type === 'agent')
  expect(agent?.parameters.userQuestion).toMatchObject({ kind: 'reference', selector: { namespace: 'inputs', path: ['question'] } })
  expect(agent?.resourceReferences.map((resource) => resource.bindingRole)).toEqual(expect.arrayContaining(['ai_model', 'ai_tool']))
  expect(payload.definition.end.outputs.answer?.value).toMatchObject({ kind: 'reference', selector: { namespace: 'outputs', port: 'main', path: ['text'] } })
  const savedResponse = await savedResponsePromise
  expect(savedResponse.status(), await savedResponse.text()).toBe(200)
  await page.getByRole('link', { name: '返回', exact: true }).click()
  await expect(page.getByText('资源与授权校验通过')).toBeVisible()
  const versionResponsePromise = page.waitForResponse((response) => response.request().method() === 'POST' && /\/workflows\/[^/]+\/versions$/.test(response.url()))
  await page.getByRole('button', { name: '创建版本' }).click()
  const versionResponse = await versionResponsePromise
  const versionBody = await versionResponse.text()
  expect(versionBody, `create version failed with ${versionResponse.status()}`).toMatch(/./)
  expect(versionResponse.status(), versionBody).toBe(201)
  await expect(page.getByText('v1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '发布', exact: true }).first().click()
  const publish = await dialog(page, '发布')
  await select(publish, '选择环境', 'Development')
  await select(publish, '选择版本', 'v1')
  await submit(publish, '发布')
  await expect(page.getByText(/Development · v1/)).toBeVisible()
}

async function verifyThemeLocaleAndRbac(page: Page, browser: Browser) {
  await page.getByRole('button', { name: '主题' }).click()
  await page.getByRole('menuitemradio', { name: '深色' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.getByRole('button', { name: '语言' }).click()
  await page.getByRole('menuitemradio', { name: 'English' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await page.reload()
  await loginIfNeeded(page)
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  const englishNavigation = page.locator('nav')
  for (const label of ['Workflows', 'Playground', 'Skills', 'Memory']) {
    await expect(englishNavigation.getByRole('link', { name: label, exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: 'Language' }).click()
  await page.getByRole('menuitemradio', { name: '简体中文' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await page.reload()
  await loginIfNeeded(page)
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  const chineseNavigation = page.locator('nav')
  for (const label of ['工作流', '调试台', '技能', '记忆']) {
    await expect(chineseNavigation.getByRole('link', { name: label, exact: true })).toBeVisible()
  }
  for (const label of ['Workflow', 'Playground', 'Skill', 'Memory']) {
    await expect(chineseNavigation.getByRole('link', { name: label, exact: true })).toHaveCount(0)
  }

  await page.getByRole('link', { name: '部门与用户' }).click()
  await page.getByRole('button', { name: '创建用户' }).click()
  const user = await dialog(page, '创建用户')
  await (await field(user, '用户名')).fill('e2e.member')
  await (await field(user, '用户名称')).fill('E2E Member')
  await submit(user, '保存')

  const memberContext = await browser.newContext({ baseURL: page.url().split('/').slice(0, 3).join('/') })
  const member = await memberContext.newPage()
  await member.goto('/login')
  await member.getByLabel('用户名').fill('e2e.member')
  await member.getByLabel('密码').fill('123456')
  await member.getByRole('button', { name: '登录' }).click()
  await member.getByLabel('新密码', { exact: true }).fill('agentx-e2e-member-password')
  await member.getByLabel('确认新密码', { exact: true }).fill('agentx-e2e-member-password')
  await member.getByRole('button', { name: '更新密码并登录' }).click()
  await expect(member).toHaveURL(/\/$/)
  await member.goto('/mcp')
  await expect(member).toHaveURL(/\/403$/)
  await expect(member.getByRole('heading', { name: '无权访问' })).toBeVisible()
  await memberContext.close()
}

async function verifyApplicationSlugUniqueness(page: Page) {
  await page.getByRole('link', { name: '应用', exact: true }).click()
  await page.getByRole('button', { name: '新建应用' }).click()
  const application = await dialog(page, '新建应用')
  await select(application, '工作流', 'MCP Echo Workflow')
  await (await field(application, '名称')).fill('唯一性 E2E 应用')
  await (await field(application, 'Slug')).fill('uniqueness-e2e')
  await submit(application, '保存')
  await expect(page.getByRole('heading', { name: '唯一性 E2E 应用' })).toBeVisible()

  await page.goto('/applications')
  await page.getByRole('button', { name: '语言' }).click()
  await page.getByRole('menuitemradio', { name: 'English' }).click()
  await page.getByRole('button', { name: 'New application' }).click()
  const duplicate = await dialog(page, 'New application')
  await select(duplicate, 'Workflows', 'MCP Echo Workflow')
  await (await field(duplicate, 'Name')).fill('Duplicate Slug Application')
  await (await field(duplicate, 'Slug')).fill('uniqueness-e2e')
  await duplicate.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(duplicate.getByText('An application with this slug already exists.')).toBeVisible()
  await expect(await field(duplicate, 'Slug')).toHaveAttribute('aria-invalid', 'true')
  await duplicate.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Language' }).click()
  await page.getByRole('menuitemradio', { name: '简体中文' }).click()
}

async function verifyIamAndEnvironmentUniqueness(page: Page) {
  await page.getByRole('link', { name: '部门与用户' }).click()
  await page.getByRole('button', { name: '新建部门' }).click()
  let form = await dialog(page, `在“${company}”下新建部门`)
  await (await field(form, '名称')).fill('唯一性部门')
  await submit(form, '保存')
  await page.getByRole('button', { name: '新建部门' }).click()
  form = await dialog(page, `在“${company}”下新建部门`)
  await (await field(form, '名称')).fill('唯一性部门')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('所选上级部门下已存在同名部门。')).toBeVisible()
  await expect(await field(form, '名称')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()

  await page.getByRole('button', { name: '创建用户' }).click()
  form = await dialog(page, '创建用户')
  await (await field(form, '用户名')).fill('e2e.member')
  await (await field(form, '用户名称')).fill('Duplicate member')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('该用户名已被使用。')).toBeVisible()
  await expect(await field(form, '用户名')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()

  await page.getByRole('link', { name: '角色权限' }).click()
  await page.getByRole('button', { name: '新建角色' }).click()
  form = await dialog(page, '新建角色')
  await (await field(form, '名称')).fill('唯一性角色')
  await (await field(form, '角色标识')).fill('uniqueness_role')
  await submit(form, '保存')
  await page.getByRole('button', { name: '新建角色' }).click()
  form = await dialog(page, '新建角色')
  await (await field(form, '名称')).fill('重复角色')
  await (await field(form, '角色标识')).fill('uniqueness_role')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('该角色编码已存在。')).toBeVisible()
  await expect(await field(form, '角色标识')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()

  await page.goto('/environments')
  await page.getByRole('button', { name: '新建环境' }).click()
  form = await dialog(page, '新建环境')
  await (await field(form, '环境标识')).fill('uniqueness')
  await (await field(form, '环境名称')).fill('唯一性环境')
  await submit(form, '保存')
  await page.getByRole('button', { name: '新建环境' }).click()
  form = await dialog(page, '新建环境')
  await (await field(form, '环境标识')).fill('uniqueness')
  await (await field(form, '环境名称')).fill('重复环境')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('该环境编码已存在。')).toBeVisible()
  await expect(await field(form, '环境标识')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()
}

async function verifyDatasetUniqueness(page: Page) {
  await page.getByRole('link', { name: '测试集' }).click()
  await page.getByRole('button', { name: '新建测试集' }).click()
  let form = await dialog(page, '新建测试集')
  await (await field(form, '名称')).fill('唯一性测试集')
  await submit(form, '保存')
  await page.getByRole('button', { name: '新增用例' }).click()
  form = await dialog(page, '新增用例')
  await (await field(form, '用例标识')).fill('case-001')
  await (await field(form, '名称')).fill('第一个用例')
  await submit(form, '保存')
  await page.getByRole('button', { name: '新增用例' }).click()
  form = await dialog(page, '新增用例')
  await (await field(form, '用例标识')).fill('case-001')
  await (await field(form, '名称')).fill('重复用例')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('测试集中已存在相同的用例 Key。')).toBeVisible()
  await expect(await field(form, '用例标识')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()
}

async function verifyExternalResourceUniqueness(page: Page) {
  await page.getByRole('link', { name: '知识库' }).click()
  await page.getByRole('button', { name: '接入知识库' }).click()
  let form = await dialog(page, '接入知识库')
  await (await field(form, '连接名称')).fill('唯一性知识连接')
  await (await field(form, 'Endpoint')).fill(lightRagBaseUrl)
  await select(form, '所属部门', company)
  await (await field(form, '资源名称')).fill('知识资源一')
  await (await field(form, '外部资源 ID')).fill('knowledge-001')
  await submit(form, '保存')
  await page.getByRole('button', { name: '添加知识资源' }).click()
  form = await dialog(page, '添加知识资源')
  await select(form, '现有连接', '唯一性知识连接')
  await select(form, '所属部门', company)
  await (await field(form, '资源名称')).fill('知识资源二')
  await (await field(form, '外部资源 ID')).fill('knowledge-001')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('所选连接下已存在相同的外部知识资源 ID。')).toBeVisible()
  await expect(await field(form, '外部资源 ID')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()

  await page.getByRole('link', { name: '记忆' }).click()
  await page.getByRole('button', { name: '接入记忆服务' }).click()
  form = await dialog(page, '接入记忆服务')
  await (await field(form, '连接名称')).fill('唯一性记忆连接')
  await (await field(form, 'Endpoint')).fill(mem0BaseUrl)
  await select(form, '所属部门', company)
  await (await field(form, '资源名称')).fill('记忆资源一')
  await (await field(form, '记忆命名空间')).fill('memory-001')
  await submit(form, '保存')
  await page.getByRole('button', { name: '添加记忆命名空间' }).click()
  form = await dialog(page, '添加记忆命名空间')
  await select(form, '现有连接', '唯一性记忆连接')
  await select(form, '所属部门', company)
  await (await field(form, '资源名称')).fill('记忆资源二')
  await (await field(form, '记忆命名空间')).fill('memory-001')
  await form.getByRole('button', { name: '保存' }).click()
  await expect(form.getByText('所选连接下已存在相同的外部 Namespace。')).toBeVisible()
  await expect(await field(form, '记忆命名空间')).toHaveAttribute('aria-invalid', 'true')
  await form.getByRole('button', { name: '取消' }).click()
}

test('required form fields show markers and actionable errors', async ({ page }) => {
  await bootstrap(page)
  await page.getByRole('link', { name: '模型服务', exact: true }).click()
  await page.getByRole('button', { name: '新建模型' }).click()
  const create = await dialog(page, '新建模型')
  await expect(create.locator('label').filter({ hasText: '连接名称' }).getByText('*', { exact: true })).toBeVisible()
  await expect(create.locator('label').filter({ hasText: 'API 格式' }).getByText('*', { exact: true })).toBeVisible()
  await expect(create.locator('label').filter({ hasText: '所属部门' }).getByText('*', { exact: true })).toBeVisible()
  await create.getByRole('button', { name: '保存', exact: true }).click()
  await expect(create.getByText('此项为必填项', { exact: true }).first()).toBeVisible()
  await expect(await field(create, '连接名称')).toBeFocused()
  await expect(await field(create, '连接名称')).toHaveAttribute('aria-invalid', 'true')
  await expect(create.getByText('Unprocessable Entity', { exact: true })).toHaveCount(0)
})

test('M2.1 control plane works through real UI actions', async ({ browser, page }) => {
  await bootstrap(page)
  await createWorkflow(page)
  await createCredentialAndVerifyConflict(page)
  await createAndReviseModel(page)
  await createAndExerciseMcp(page)
  await createSkillWorkspace(page)
  await configureCentralResourceGrants(page)
  await configureAndPublishWorkflow(page)
  await verifyApplicationSlugUniqueness(page)
  await verifyThemeLocaleAndRbac(page, browser)
  await verifyIamAndEnvironmentUniqueness(page)
  await verifyDatasetUniqueness(page)
  await verifyExternalResourceUniqueness(page)
})
