import { expect, type Locator, type Page, test } from '@playwright/test'

const password = 'agentx-e2e-admin-password'

async function login(page: Page) { await page.goto('/login'); await page.getByLabel('用户名').fill('admin'); await page.getByLabel('密码').fill(password); await page.getByRole('button', { name: '登录' }).click(); await expect(page).toHaveURL(/\/$/) }
async function dialog(page: Page, title: string) { const value=page.getByRole('dialog',{name:title});await expect(value).toBeVisible();return value }
async function field(container: Locator, label: string) { return container.locator('label').filter({hasText:label}).locator('input, textarea').first() }
async function select(container: Locator,label:string,option:string){await container.getByRole('combobox',{name:label,exact:true}).click();await container.page().getByRole('option',{name:option,exact:true}).click()}
async function submit(container:Locator,name='保存'){await container.getByRole('button',{name,exact:true}).click();await expect(container).toBeHidden()}

test('M3 application, gateway, dataset, and evaluation control planes use real UI actions', async ({ page, browser }) => {
  await login(page)
  await page.getByRole('link',{name:'应用',exact:true}).click()
  await page.getByRole('button',{name:'新建应用'}).click()
  const application=await dialog(page,'新建应用')
  await select(application,'工作流','MCP Echo Workflow')
  await (await field(application,'名称')).fill('M3 E2E Application')
  await (await field(application,'Slug')).fill('m3-e2e')
  await submit(application)
  await expect(page.getByRole('heading',{name:'M3 E2E Application'})).toBeVisible()
  await page.goto('/applications')
  await page.getByRole('row',{name:/M3 E2E Application/}).getByRole('link',{name:'管理'}).click()
  await page.getByRole('button',{name:'编辑',exact:true}).click()
  const editApplication=await dialog(page,'编辑应用')
  await (await field(editApplication,'描述')).fill('M3 application updated through the UI')
  await submit(editApplication)
  await page.getByRole('button',{name:'编辑',exact:true}).click()
  const verifyApplication=await dialog(page,'编辑应用')
  await expect(await field(verifyApplication,'描述')).toHaveValue('M3 application updated through the UI')
  await verifyApplication.getByRole('button',{name:'取消'}).click()

  await page.getByRole('button',{name:'创建部署'}).click()
  const deployment=await dialog(page,'部署')
  await select(deployment,'工作流版本','v1')
  await select(deployment,'环境','Development')
  await submit(deployment)
  await expect(page.getByText('Development · v1')).toBeVisible()

  await page.getByRole('tab',{name:'API Keys'}).click()
  await page.getByRole('button',{name:'API 接入文档'}).click()
  const apiGuide=await dialog(page,'API Key 接入文档')
  await expect(apiGuide.getByText(/\/gateway\/v1\/applications\/m3-e2e\/invocations/)).toBeVisible()
  await apiGuide.getByRole('tab',{name:'数据结构'}).click()
  await expect(apiGuide.getByText('工作流输入 Schema')).toBeVisible()
  await apiGuide.getByRole('button',{name:'关闭'}).click()
  await page.getByRole('button',{name:'创建 API Key'}).click()
  const key=await dialog(page,'API Key')
  await (await field(key,'名称')).fill('M3 E2E Key')
  await submit(key)
  await expect(page.locator('code').filter({ hasText: /^axk_/ })).toBeVisible()
  await page.getByRole('button',{name:'轮换'}).click()
  let keyConfirmation=await dialog(page,'轮换 API Key')
  await keyConfirmation.getByRole('button',{name:'取消'}).click()
  await expect(keyConfirmation).toBeHidden()
  await page.getByRole('button',{name:'轮换'}).click()
  keyConfirmation=await dialog(page,'轮换 API Key')
  await keyConfirmation.getByRole('button',{name:'轮换'}).click()
  await expect(keyConfirmation).toBeHidden()
  await page.getByRole('button',{name:'撤销'}).click()
  keyConfirmation=await dialog(page,'撤销 API Key')
  await keyConfirmation.getByRole('button',{name:'取消'}).click()
  await expect(keyConfirmation).toBeHidden()
  await page.getByRole('button',{name:'撤销'}).click()
  keyConfirmation=await dialog(page,'撤销 API Key')
  await keyConfirmation.getByRole('button',{name:'撤销'}).click()
  await expect(keyConfirmation).toBeHidden()

  await page.getByRole('tab',{name:'触发器'}).click()
  await page.getByRole('button',{name:'Webhook 接入文档'}).click()
  const genericWebhookGuide=await dialog(page,'Webhook 接入文档')
  await expect(genericWebhookGuide.getByText(/\/gateway\/v1\/webhooks\/\{public_id\}/)).toBeVisible()
  await genericWebhookGuide.getByRole('tab',{name:'数据结构'}).click()
  await expect(genericWebhookGuide.getByText('工作流输入 Schema')).toBeVisible()
  await genericWebhookGuide.getByRole('button',{name:'关闭'}).click()
  await page.getByRole('button',{name:'新建'}).first().click()
  const webhook=await dialog(page,'Webhook')
  await (await field(webhook,'名称')).fill('M3 Hook')
  await submit(webhook)
  await expect(page.getByText('/gateway/v1/webhooks/')).toBeVisible()
  await expect(page.locator('code')).toHaveCount(1)
  const webhookRow=page.getByRole('group',{name:'M3 Hook'})
  await webhookRow.getByRole('button',{name:'查看接入'}).click()
  const webhookGuide=await dialog(page,'Webhook 接入文档')
  await expect(webhookGuide.getByText(/\/gateway\/v1\/webhooks\//).first()).toBeVisible()
  await webhookGuide.getByRole('tab',{name:'安全说明'}).click()
  await expect(webhookGuide.getByText(/Base64UrlNoPadding/)).toBeVisible()
  await webhookGuide.getByRole('button',{name:'关闭'}).click()
  await webhookRow.getByRole('button',{name:'编辑'}).click()
  const editWebhook=await dialog(page,'编辑 Webhook')
  await select(editWebhook,'状态','停用')
  await submit(editWebhook)
  await expect(webhookRow.getByText('停用')).toBeVisible()
  await page.getByRole('button',{name:'新建'}).last().click()
  const schedule=await dialog(page,'定时触发')
  await (await field(schedule,'名称')).fill('M3 Morning')
  await submit(schedule)
  await expect(page.getByText(/0 9 \* \* 1/)).toBeVisible()
  const scheduleRow=page.getByRole('group',{name:'M3 Morning'})
  await scheduleRow.getByRole('button',{name:'编辑'}).click()
  const editSchedule=await dialog(page,'编辑定时触发')
  await select(editSchedule,'状态','启用')
  await submit(editSchedule)
  await expect(scheduleRow.getByText('启用')).toBeVisible()

  await page.getByRole('link',{name:'调试台',exact:true}).click()
  await page.getByRole('combobox').click();await page.getByRole('option',{name:'M3 E2E Application'}).click()
  await page.getByRole('tab',{name:'对话测试'}).click()
  await page.getByRole('button',{name:'新建会话'}).click()
  await expect(page.getByText('调试台会话', { exact: true })).toBeVisible()
  await expect(page.getByPlaceholder('请先配置对话参数映射')).toBeVisible()
  await page.getByRole('button',{name:'参数映射'}).click()
  const mapping = await dialog(page,'对话参数映射')
  await mapping.getByRole('combobox',{name:'文件输入'}).click()
  await page.getByRole('option',{name:/attachments.*artifact/}).click()
  await mapping.getByRole('button',{name:'保存并发布'}).click()
  await expect(mapping).toBeHidden()
  await expect(page.getByText(/映射 v\d+/)).toBeVisible({timeout:120_000})
  const composer = page.getByPlaceholder('输入消息进行测试…')
  await expect(composer).toBeEnabled()
  await page.locator('input[type=file]').setInputFiles({name:'m3-question.png',mimeType:'image/png',buffer:Buffer.from('M3 file input')})
  await expect(page.getByText('m3-question.png',{exact:true})).toBeVisible()
  await composer.fill('M3 runtime integration')
  const invocationResponse = page.waitForResponse((response) => response.url().includes('/gateway/v1/sessions/') && response.url().endsWith('/messages') && response.request().method() === 'POST')
  await page.getByRole('button',{name:'发送'}).click()
  expect((await invocationResponse).status()).toBe(202)
  await expect(page.getByText('已完成',{exact:true})).toBeVisible({timeout:180_000})
  await expect(page.getByRole('link',{name:'执行详情 / Trace'})).toBeVisible()

  await page.getByRole('link',{name:'应用',exact:true}).click()
  await page.getByRole('row',{name:/M3 E2E Application/}).getByRole('link',{name:'管理'}).click()
  await page.getByRole('tab',{name:'会话'}).click()
  const sessionRow=page.getByRole('group',{name:'M3 runtime integration'})
  await expect(sessionRow.getByText('启用',{exact:true})).toBeVisible()
  await sessionRow.getByRole('link',{name:'打开会话'}).click()
  await expect(page).toHaveURL(/\/playground\?applicationId=.+&mode=conversation&sessionId=.+/)
  await expect(page.getByText('M3 runtime integration',{exact:true}).first()).toBeVisible()

  await page.getByRole('link',{name:'测试集',exact:true}).click()
  await page.getByRole('button',{name:'新建测试集'}).click()
  const dataset=await dialog(page,'新建测试集')
  await (await field(dataset,'名称')).fill('M3 E2E Dataset')
  await submit(dataset)
  await page.getByRole('button',{name:'发布版本'}).click()
  const datasetPrerequisites=await dialog(page,'创建前需要完成')
  await expect(datasetPrerequisites.getByText('测试集至少包含一个用例')).toBeVisible()
  await datasetPrerequisites.getByRole('button',{name:'新增用例'}).click()
  const testCase=await dialog(page,'新增用例')
  await (await field(testCase,'用例标识')).fill('echo-001')
  await (await field(testCase,'名称')).fill('Echo regression')
  await (await field(testCase,'输入 JSON')).fill('{"question":"hello","attachments":[]}')
  await (await field(testCase,'预期输出 JSON')).fill('{"text":"hello"}')
  await submit(testCase)
  const caseRow=page.getByRole('row').filter({hasText:'echo-001'})
  await caseRow.getByRole('button',{name:'编辑'}).click()
  const editCase=await dialog(page,'编辑用例')
  await (await field(editCase,'名称')).fill('Echo regression updated')
  await submit(editCase)
  await expect(caseRow.getByText('Echo regression updated')).toBeVisible()
  const badImport=Buffer.from('{"caseKey":"valid","name":"Valid","input":{}}\nnot-json')
  await page.locator('input[type=file]').setInputFiles({name:'invalid.jsonl',mimeType:'application/x-ndjson',buffer:badImport})
  await expect(page.getByText('请求失败（INVALID_DATASET_IMPORT）', { exact: true })).toBeVisible()
  await expect(page.getByRole('row').filter({hasText:'valid'})).toHaveCount(0)
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('button',{name:'导出'}).click()
  await downloadPromise
  await page.getByRole('button',{name:'发布版本'}).click()
  await expect(page.getByText('不可变版本已发布',{exact:true})).toBeVisible()
  await caseRow.getByRole('button',{name:'删除用例'}).click()
  let deleteConfirmation=await dialog(page,'删除用例')
  await deleteConfirmation.getByRole('button',{name:'取消'}).click()
  await expect(caseRow).toBeVisible()
  await caseRow.getByRole('button',{name:'删除用例'}).click()
  deleteConfirmation=await dialog(page,'删除用例')
  await deleteConfirmation.getByRole('button',{name:'删除'}).click()
  await expect(caseRow).toHaveCount(0)

  await page.getByRole('link',{name:'评测报告',exact:true}).click()
  await page.getByRole('tab',{name:'评测方案',exact:true}).click()
  await page.getByRole('button',{name:'新建评测方案'}).click()
  const profile=await dialog(page,'新建评测方案')
  await (await field(profile,'名称')).fill('M3 Regression')
  await (await field(profile,'规则名称')).fill('Exact output')
  await profile.getByRole('button',{name:'添加规则'}).click()
  await profile.locator('label').filter({hasText:'规则名称'}).locator('input').nth(1).fill('Contains output')
  await profile.locator('label').filter({hasText:'规则标识'}).locator('input').nth(1).fill('contains_output')
  await profile.getByRole('combobox',{name:'规则类型'}).nth(1).click()
  await page.getByRole('option',{name:'包含文本'}).click()
  await submit(profile)
  await expect(page.getByText(/v1 · 2 评分规则/)).toBeVisible()
  await page.getByRole('tab',{name:'评测报告',exact:true}).click()
  await page.getByRole('button',{name:'发起评测'}).click()
  const run=await dialog(page,'评测配置')
  await (await field(run,'名称')).fill('M3 Runtime Boundary')
  await select(run,'工作流版本','MCP Echo Workflow · v1')
  await select(run,'测试集','M3 E2E Dataset · v1')
  await select(run,'评测方案','M3 Regression · v1')
  await submit(run)
  await page.getByRole('button',{name:'开始评测'}).click()
  await expect(page.getByText('已完成',{exact:true}).first()).toBeVisible({timeout:180_000})
  await expect(page.getByRole('link',{name:'Trace'}).first()).toBeVisible()

  const memberContext=await browser.newContext({baseURL:page.url().split('/').slice(0,3).join('/')})
  const member=await memberContext.newPage()
  await member.goto('/login')
  await member.getByLabel('用户名').fill('e2e.member')
  await member.getByLabel('密码').fill('agentx-e2e-member-password')
  await member.getByRole('button',{name:'登录'}).click()
  await expect(member).toHaveURL(/\/$/)
  await member.goto('/applications')
  await expect(member.getByRole('heading',{name:'应用',exact:true})).toBeVisible()
  await expect(member.getByRole('button',{name:'新建应用'})).toHaveCount(0)
  await member.goto('/datasets')
  await expect(member).toHaveURL(/\/403$/)
  await memberContext.close()
})
