apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: control-default-deny
  namespace: {{ .Values.global.namespaces.control }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
