apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-control
  namespace: {{ .Values.global.namespaces.control }}
automountServiceAccountToken: false
{{- with .Values.global.images.pullSecretName }}
imagePullSecrets: [{ name: {{ . }} }]
{{- end }}
