import { AlignHorizontalJustifyStart, AlignVerticalJustifyStart, ArrowLeft, GitBranch, LayoutDashboard, ListTree, Play, Redo2, Rocket, Save, Square, Undo2 } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { Button } from '../../../shared/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../../../shared/ui/dropdown-menu'
import { Select } from '../../../shared/ui/select'
import { Tooltip } from '../../../shared/ui/tooltip'

export function StudioToolbar({ workflowId, name, revision, dirty, saving, running, mode, canUndo, canRedo, selectedCount, onMode, onSave, onRun, onStop, onUndo, onRedo, onLayout, onAlign, onVersion, onPublish }: { workflowId: string; name: string; revision: number; dirty: boolean; saving: boolean; running: boolean; mode: string; canUndo: boolean; canRedo: boolean; selectedCount: number; onMode: (mode: string) => void; onSave: () => void; onRun: () => void; onStop: () => void; onUndo: () => void; onRedo: () => void; onLayout: () => void; onAlign: (direction: 'left' | 'top') => void; onVersion: () => void; onPublish: () => void }) {
  const { t } = useTranslation()
  return <header className="flex h-14 shrink-0 items-center gap-2 border-b border-border bg-surface px-3">
    <Tooltip content={t('studio.back')}><Button asChild size="icon" variant="ghost"><Link aria-label={t('studio.back')} to={`/workflows/${workflowId}`}><ArrowLeft className="size-4" /></Link></Button></Tooltip><div className="mx-1 h-6 w-px bg-border" /><div className="min-w-0"><h1 className="max-w-64 truncate text-xs font-semibold">{name}</h1><p className="mt-0.5 text-[9px] text-muted-foreground">{t(dirty ? 'studio.revisionUnsaved' : 'studio.revisionSaved', { revision })}</p></div><div className="flex-1" />
    <Tooltip content={t('studio.undo')}><Button aria-label={t('studio.undo')} disabled={!canUndo} onClick={onUndo} size="icon" variant="ghost"><Undo2 className="size-4" /></Button></Tooltip><Tooltip content={t('studio.redo')}><Button aria-label={t('studio.redo')} disabled={!canRedo} onClick={onRedo} size="icon" variant="ghost"><Redo2 className="size-4" /></Button></Tooltip><DropdownMenu><DropdownMenuTrigger asChild><Button aria-label={t('studio.align')} disabled={selectedCount < 2} size="icon" variant="ghost"><ListTree className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onAlign('left')}><AlignHorizontalJustifyStart className="size-4" />{t('studio.alignLeft')}</DropdownMenuItem><DropdownMenuItem onSelect={() => onAlign('top')}><AlignVerticalJustifyStart className="size-4" />{t('studio.alignTop')}</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Tooltip content={t('studio.autoLayout')}><Button aria-label={t('studio.autoLayout')} onClick={onLayout} size="icon" variant="ghost"><LayoutDashboard className="size-4" /></Button></Tooltip>
    <Button disabled={!dirty || saving} onClick={onSave} size="sm" variant="secondary"><Save className="size-3.5" />{t('studio.save')}</Button><Button disabled={dirty || saving} onClick={onVersion} size="sm" variant="secondary"><GitBranch className="size-3.5" />{t('studio.version')}</Button><Button disabled={dirty || saving} onClick={onPublish} size="sm" variant="secondary"><Rocket className="size-3.5" />{t('studio.publish')}</Button>
    <Select aria-label={t('studio.debug.title')} className="w-32" onValueChange={onMode} options={[{ value: 'full', label: t('studio.modes.full') }, { value: 'single_node', label: t('studio.modes.single') }, { value: 'to_node', label: t('studio.modes.toNode') }, { value: 'from_node', label: t('studio.modes.fromNode') }]} value={mode} />
    {running ? <Button onClick={onStop} size="sm" variant="secondary"><Square className="size-3.5" />{t('studio.stop')}</Button> : <Button disabled={dirty || saving} onClick={onRun} size="sm"><Play className="size-3.5" />{t('studio.run')}</Button>}
  </header>
}
