import { Eye, GitCommitHorizontal, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import type { WorkflowVersion } from '../../../shared/api/types'
import { Button } from '../../../shared/ui/button'
import { Dialog, DialogContent } from '../../../shared/ui/dialog'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../../shared/ui/tabs'
import type { EditorDocument, WorkflowDefinition } from '../model/types'
import { definitionDiff } from '../model/version-diff'

export function VersionDialog({ open, versions, definition, editorDocument, creating, onClose, onCreate }: { open: boolean; versions: WorkflowVersion[]; definition: WorkflowDefinition; editorDocument: EditorDocument; creating: boolean; onClose: () => void; onCreate: () => void }) {
  const { t } = useTranslation()
  const [selectedId, setSelectedId] = useState<string>()
  const latest = versions[0]
  const selected = versions.find((version) => version.id === selectedId) ?? latest
  const diff = useMemo(() => definitionDiff(latest?.definition as WorkflowDefinition | undefined, definition, latest?.editorDocument as EditorDocument | undefined, editorDocument), [definition, editorDocument, latest])
  return <Dialog onOpenChange={(value) => !value && onClose()} open={open}><DialogContent className="w-[min(920px,calc(100vw-48px))]" title={t('studio.versionDialog.title')}><div className="p-5"><div className="flex items-center"><div><h2 className="text-sm font-semibold">{t('studio.versionDialog.title')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('studio.versionDialog.description')}</p></div><span className="flex-1" /><Button disabled={creating || diff.definitionChanges === 0 && diff.editorChanges === 0} onClick={onCreate}><Plus className="size-4" />{t('studio.versionDialog.create')}</Button></div><Tabs className="mt-5" defaultValue="diff"><TabsList><TabsTrigger value="diff">{t('studio.versionDialog.diff')}</TabsTrigger><TabsTrigger value="history">{t('studio.versionDialog.history')}</TabsTrigger></TabsList><TabsContent className="pt-4" value="diff"><div className="grid grid-cols-4 divide-x divide-border border-y border-border py-4 text-center"><Metric label={t('studio.versionDialog.nodes')} value={diff.nodeSummary} /><Metric label={t('studio.versionDialog.connections')} value={diff.connectionSummary} /><Metric label={t('studio.versionDialog.definitionChanges')} value={String(diff.definitionChanges)} /><Metric label={t('studio.versionDialog.editorChanges')} value={String(diff.editorChanges)} /></div><pre className="mt-4 max-h-72 overflow-auto bg-canvas p-3 font-mono text-[10px] leading-5 text-muted-foreground">{JSON.stringify({ definition, editorDocument }, null, 2)}</pre></TabsContent><TabsContent className="pt-4" value="history"><div className="grid min-h-72 grid-cols-[260px_minmax(0,1fr)] border border-border"><div className="border-r border-border">{versions.map((version) => <button className={`flex w-full items-center gap-3 border-b border-border px-3 py-3 text-left text-xs ${selected?.id === version.id ? 'bg-primary/10 text-primary' : 'hover:bg-muted/50'}`} key={version.id} onClick={() => setSelectedId(version.id)} type="button"><GitCommitHorizontal className="size-4" /><span><strong className="block">{t('studio.versionDialog.version', { version: version.versionNumber })}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{t('studio.versionDialog.revision', { revision: version.sourceRevision })}</span></span><Eye className="ml-auto size-3.5" /></button>)}</div><pre className="max-h-80 overflow-auto p-3 font-mono text-[10px] leading-5 text-muted-foreground">{JSON.stringify(selected ? { definition: selected.definition, editorDocument: selected.editorDocument } : {}, null, 2)}</pre></div></TabsContent></Tabs><div className="mt-5 flex justify-end"><Button onClick={onClose} variant="secondary">{t('studio.versionDialog.close')}</Button></div></div></DialogContent></Dialog>
}

function Metric({ label, value }: { label: string; value: string }) { return <div><strong className="text-sm">{value}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{label}</span></div> }
