[package]
name = "agentx-application"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
agentx-domain.workspace = true
agentx-runtime-contracts.workspace = true
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio-util.workspace = true
uuid.workspace = true
zeroize.workspace = true
