[package]
name = "workflow-coordinator"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
agentx-application.workspace = true
agentx-infrastructure.workspace = true
agentx-runtime-rpc.workspace = true
agentx-service-kit.workspace = true
anyhow.workspace = true
axum.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
