import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { ColumnDef } from '@tanstack/react-table'
import { MemoryStick, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'

import { useAuth } from '../../app/providers/auth-provider'
import { apiRequest, jsonBody } from '../../shared/api/client'
import type { Credential, Department, ExternalConnection, MemoryResource, PageResponse } from '../../shared/api/types'
import { EntityCell } from '../../shared/components/entity-cell'
import { EntityDeleteButton } from '../../shared/components/entity-delete-button'
import { EntityFormDialog, type EntityFormField } from '../../shared/components/entity-form-dialog'
import { ListPage } from '../../shared/components/list-page'
import { StatusBadge } from '../../shared/components/status-badge'
import { localizedValue } from '../../shared/lib/localized-value'
import { Button } from '../../shared/ui/button'
import { useToast } from '../../shared/ui/toast'

export function MemoryPage() {
  const { t } = useTranslation(); const auth = useAuth(); const queryClient = useQueryClient(); const { showToast } = useToast(); const [open, setOpen] = useState<'new' | 'existing'>()
  const resources = useQuery({ queryKey: ['memory'], queryFn: () => apiRequest<PageResponse<MemoryResource>>('/memory/namespaces?pageSize=100') })
  const connections = useQuery({ queryKey: ['memory-connections'], queryFn: () => apiRequest<ExternalConnection[]>('/memory/connections') })
  const departments = useQuery({ queryKey: ['departments'], queryFn: () => apiRequest<Department[]>('/departments') })
  const credentials = useQuery({ queryKey: ['credentials', 'options'], queryFn: () => apiRequest<PageResponse<Credential>>('/credentials?pageSize=100&status=active') })
  const create = useMutation({ mutationFn: async (values: Record<string, string>) => { const connectionId = values.connectionId || (await apiRequest<ExternalConnection>('/memory/connections', { method: 'POST', body: jsonBody({ name: values.connectionName, endpoint: values.endpoint, healthPath: values.healthPath, credentialId: values.credential || null, ownerDepartmentId: values.department, configuration: {} }) })).id; return apiRequest<MemoryResource>('/memory/namespaces', { method: 'POST', body: jsonBody({ connectionId, name: values.name, externalNamespace: values.externalNamespace, accessMode: values.accessMode, ownerDepartmentId: values.department }) }) }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['memory'] }), queryClient.invalidateQueries({ queryKey: ['memory-connections'] })]); showToast(t('memory.created')) } })
  const columns = useMemo<Array<ColumnDef<MemoryResource>>>(() => [
    { accessorKey: 'name', header: t('memory.title'), cell: ({ row }) => <EntityCell detail={row.original.connectionName} icon={MemoryStick} name={row.original.name} /> }, { accessorKey: 'externalNamespace', header: t('memory.namespace') }, { accessorKey: 'accessMode', header: t('memory.permission'), cell: ({ row }) => localizedValue(t, 'memory.accessModes', row.original.accessMode) }, { accessorKey: 'grantCount', header: t('memory.workflows') }, { accessorKey: 'status', header: t('common.status'), cell: ({ row }) => <StatusBadge label={localizedValue(t, 'common', row.original.status)} status={row.original.status === 'active' ? 'active' : 'inactive'} /> }, { id: 'actions', header: '', cell: ({ row }) => <div className="flex gap-1"><Button asChild size="sm" variant="ghost"><Link to={`/memory/${row.original.id}`}>{t('memory.details')}</Link></Button><EntityDeleteButton canDelete={auth.hasPermission('memory:delete')} deletePath={`/memory/namespaces/${row.original.id}`} entityId={row.original.id} entityName={row.original.name} entityType="memory" onDeleted={async () => { await queryClient.invalidateQueries({ queryKey: ['memory'] }); showToast(t('memory.deleted')) }} /></div> },
  ], [auth, queryClient, showToast, t])
  const newFields: EntityFormField[] = [{ name: 'connectionName', label: t('memory.connectionName'), required: true }, { name: 'endpoint', label: t('memory.endpoint'), required: true }, { name: 'healthPath', label: t('memory.healthPath'), defaultValue: '/health', required: true }, { name: 'credential', label: t('memory.credential'), type: 'select', options: [{ value: '', label: t('memory.noCredential') }, ...(credentials.data?.items ?? []).map((item) => ({ value: item.id, label: item.name }))] }, { name: 'department', label: t('memory.department'), type: 'select', required: true, options: (departments.data ?? []).map((item) => ({ value: item.id, label: item.name })) }, { name: 'name', label: t('memory.resourceName'), required: true }, { name: 'externalNamespace', label: t('memory.namespace'), required: true }, { name: 'accessMode', label: t('memory.accessMode'), type: 'select', defaultValue: 'read_write', required: true, options: [{ value: 'read', label: t('memory.readOnly') }, { value: 'read_write', label: t('memory.readWrite') }] }]
  const existingFields: EntityFormField[] = [{ name: 'connectionId', label: t('memory.connection'), type: 'select', required: true, options: (connections.data ?? []).map((item) => ({ value: item.id, label: item.name })) }, { name: 'department', label: t('memory.department'), type: 'select', required: true, options: (departments.data ?? []).map((item) => ({ value: item.id, label: item.name })) }, { name: 'name', label: t('memory.resourceName'), required: true }, { name: 'externalNamespace', label: t('memory.namespace'), required: true }, { name: 'accessMode', label: t('memory.accessMode'), type: 'select', defaultValue: 'read_write', required: true, options: [{ value: 'read', label: t('memory.readOnly') }, { value: 'read_write', label: t('memory.readWrite') }] }]
  return <><ListPage action={auth.hasPermission('memory:manage') ? <div className="flex gap-2">{Boolean(connections.data?.length) && <Button onClick={() => setOpen('existing')} variant="secondary">{t('memory.addNamespace')}</Button>}<Button onClick={() => setOpen('new')}><Plus className="size-4" />{t('memory.create')}</Button></div> : undefined} columns={columns} data={resources.data?.items ?? []} description={t('memory.description')} getSearchText={(row) => `${row.name} ${row.connectionName} ${row.externalNamespace}`} getStatus={(row) => row.status === 'active' ? 'active' : 'inactive'} searchPlaceholder={t('memory.search')} statusOptions={[{ value: 'active', label: t('common.active') }, { value: 'inactive', label: t('common.inactive') }]} title={t('memory.title')} />{open && <EntityFormDialog cancelLabel={t('common.cancel')} fields={open === 'new' ? newFields : existingFields} onClose={() => setOpen(undefined)} onSubmit={(values) => create.mutateAsync(values).then(() => undefined)} open submitLabel={t('common.save')} title={open === 'new' ? t('memory.create') : t('memory.addNamespace')} />}</>
}
