-- Generated by scripts/generate-v2-initial-schema.ps1.
-- V2-01 uses empty databases: do not append the V1 migration chain here.
-- Cross-plane relations are logical references and therefore have no FKs.
SET NAMES utf8mb4;
SET time_zone = '+00:00';
CREATE TABLE application_api_keys (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    family_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    key_prefix VARCHAR(48) NOT NULL,
    secret_hash BINARY(32) NOT NULL,
    status ENUM('active', 'revoked') NOT NULL DEFAULT 'active',
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_used_at TIMESTAMP(6) NULL,
    revoked_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_application_api_key_prefix (key_prefix),
    KEY idx_application_api_keys (tenant_id, application_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_deployment_heads (
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    deployment_id BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, application_id),
    UNIQUE KEY uq_application_deployment_head (deployment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_deployments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    input_schema_json JSON NOT NULL,
    output_schema_json JSON NOT NULL,
    session_version_policy ENUM('pinned', 'follow_deployment', 'manual_upgrade') NOT NULL DEFAULT 'pinned',
    status ENUM('active', 'superseded') NOT NULL DEFAULT 'active',
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_application_deployment_sequence (tenant_id, application_id, sequence_number),
    KEY idx_application_deployment_version (tenant_id, workflow_version_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_schedules (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    cron_expression VARCHAR(128) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    input_json JSON NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'disabled',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_application_schedules (tenant_id, application_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE application_webhooks (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    application_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    public_id VARCHAR(64) NOT NULL,
    secret_algorithm VARCHAR(32) NOT NULL,
    secret_key_id VARCHAR(64) NOT NULL,
    secret_nonce VARBINARY(32) NOT NULL,
    secret_ciphertext BLOB NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_application_webhook_public (public_id),
    KEY idx_application_webhooks (tenant_id, application_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE applications (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(96) NOT NULL,
    description VARCHAR(1000) NULL,
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    owner_user_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('draft', 'active', 'disabled') NOT NULL DEFAULT 'draft',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_application_slug (tenant_id, slug),
    KEY idx_applications_tenant (tenant_id, status, updated_at),
    KEY idx_applications_department (tenant_id, owner_department_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_action_submissions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    approval_task_id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NOT NULL,
    action_type ENUM('claim', 'release', 'reassign', 'approve', 'reject', 'cancel', 'timeout') NOT NULL,
    input_json JSON NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_approval_actions_task (tenant_id, approval_task_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_candidate_projection (
    tenant_id BINARY(16) NOT NULL,
    approval_task_id BINARY(16) NOT NULL,
    candidate_type ENUM('user', 'role', 'department') NOT NULL,
    candidate_id BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, approval_task_id, candidate_type, candidate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE approval_task_projection (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NULL,
    request_payload_json JSON NULL,
    status ENUM('pending', 'claimed', 'approved', 'rejected', 'cancelled', 'timed_out') NOT NULL DEFAULT 'pending',
    claimed_by BINARY(16) NULL,
    claimed_at TIMESTAMP(6) NULL,
    resume_status ENUM('not_requested', 'pending', 'succeeded', 'blocked_runtime', 'failed') NOT NULL DEFAULT 'not_requested',
    deadline_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_approval_tasks_inbox (tenant_id, status, deadline_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE artifact_references (
    tenant_id BINARY(16) NOT NULL,
    artifact_id BINARY(16) NOT NULL,
    owner_type VARCHAR(64) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    reference_role VARCHAR(64) NOT NULL,
    retention_until TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, artifact_id, owner_type, owner_id, reference_role),
    KEY idx_artifact_reference_owner (tenant_id, owner_type, owner_id),
    KEY idx_artifact_reference_retention (tenant_id, artifact_id, retention_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE artifacts (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_artifacts_storage_key (storage_key),
    KEY idx_artifacts_tenant_created (tenant_id, created_at),
    KEY idx_artifacts_tenant_hash (tenant_id, sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_events (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NULL,
    action VARCHAR(128) NOT NULL,
    target_type VARCHAR(128) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    request_id BINARY(16) NOT NULL,
    detail_json JSON NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_audit_tenant_time (tenant_id, occurred_at),
    KEY idx_audit_target (tenant_id, target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE auth_login_attempts (
    login_key CHAR(64) NOT NULL,
    failure_count INT UNSIGNED NOT NULL DEFAULT 0,
    window_started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_until TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (login_key),
    KEY idx_auth_login_attempts_locked (locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE bootstrap_state (
    singleton_id TINYINT UNSIGNED NOT NULL,
    state ENUM('required', 'completed') NOT NULL,
    tenant_id BINARY(16) NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (singleton_id),
    CONSTRAINT chk_bootstrap_singleton CHECK (singleton_id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE credential_secret_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    credential_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    algorithm VARCHAR(32) NOT NULL,
    key_id VARCHAR(64) NOT NULL,
    nonce VARBINARY(32) NOT NULL,
    ciphertext MEDIUMBLOB NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_credential_secret_version (tenant_id, credential_id, version_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE credentials (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    credential_type ENUM('api_key', 'bearer', 'basic', 'custom_json') NOT NULL,
    storage_mode ENUM('local_encrypted', 'external_reference') NOT NULL DEFAULT 'local_encrypted',
    masked_hint VARCHAR(32) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    current_secret_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    owner_department_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_credentials_tenant_status (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dataset_cases (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dataset_id BINARY(16) NOT NULL,
    case_key VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    input_json JSON NOT NULL,
    expected_output_json JSON NULL,
    context_json JSON NULL,
    tags_json JSON NOT NULL,
    evaluator_override_json JSON NULL,
    sort_order BIGINT UNSIGNED NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_dataset_case_key (tenant_id, dataset_id, case_key),
    KEY idx_dataset_cases_order (tenant_id, dataset_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dataset_version_cases (
    tenant_id BINARY(16) NOT NULL,
    dataset_version_id BINARY(16) NOT NULL,
    source_case_id BINARY(16) NOT NULL,
    case_key VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    input_json JSON NOT NULL,
    expected_output_json JSON NULL,
    context_json JSON NULL,
    tags_json JSON NOT NULL,
    evaluator_override_json JSON NULL,
    sort_order BIGINT UNSIGNED NOT NULL,
    content_hash CHAR(64) NOT NULL,
    PRIMARY KEY (tenant_id, dataset_version_id, source_case_id),
    KEY idx_dataset_version_case_order (tenant_id, dataset_version_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE dataset_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dataset_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    source_revision BIGINT UNSIGNED NOT NULL,
    content_hash CHAR(64) NOT NULL,
    case_count BIGINT UNSIGNED NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_dataset_version_number (tenant_id, dataset_id, version_number),
    UNIQUE KEY uq_dataset_version_hash (tenant_id, dataset_id, source_revision, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE datasets (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    owner_user_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_datasets_tenant (tenant_id, status, updated_at),
    KEY idx_datasets_department (tenant_id, owner_department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE department_closure (
    tenant_id BINARY(16) NOT NULL,
    ancestor_id BINARY(16) NOT NULL,
    descendant_id BINARY(16) NOT NULL,
    depth INT UNSIGNED NOT NULL,
    PRIMARY KEY (tenant_id, ancestor_id, descendant_id),
    KEY idx_department_closure_descendant (tenant_id, descendant_id, ancestor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE departments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    parent_id BINARY(16) NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    is_root BOOLEAN NOT NULL DEFAULT FALSE,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_departments_sibling_name (tenant_id, parent_id, normalized_name),
    KEY idx_departments_tenant_parent (tenant_id, parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE deployment_history (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    deployment_id BINARY(16) NOT NULL,
    action ENUM('published', 'superseded', 'rolled_back') NOT NULL,
    actor_user_id BINARY(16) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_deployment_history (tenant_id, workflow_id, environment_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_case_results (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    source_case_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    status ENUM('passed', 'failed', 'error', 'cancelled') NOT NULL,
    score DECIMAL(12,6) NULL,
    detail_json JSON NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_case_result (tenant_id, evaluation_run_id, source_case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_comparisons (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    baseline_run_id BINARY(16) NOT NULL,
    candidate_run_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_metrics (
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    metric_key VARCHAR(128) NOT NULL,
    metric_value DECIMAL(24,8) NOT NULL,
    detail_json JSON NULL,
    PRIMARY KEY (tenant_id, evaluation_run_id, metric_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_profile_rules (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    profile_version_id BINARY(16) NOT NULL,
    rule_key VARCHAR(128) NOT NULL,
    name VARCHAR(160) NOT NULL,
    evaluator_type ENUM('exact', 'contains', 'regex', 'json_schema', 'llm_judge', 'custom_code') NOT NULL,
    configuration_json JSON NOT NULL,
    weight DECIMAL(10,4) NOT NULL DEFAULT 1,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_profile_rule (tenant_id, profile_version_id, rule_key),
    KEY idx_evaluation_profile_rule_order (tenant_id, profile_version_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_profile_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    profile_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    aggregation ENUM('all', 'any', 'weighted') NOT NULL DEFAULT 'all',
    pass_threshold DECIMAL(8,6) NOT NULL DEFAULT 1,
    content_hash CHAR(64) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_profile_version (tenant_id, profile_id, version_number),
    UNIQUE KEY uq_evaluation_profile_version_hash (tenant_id, profile_id, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_profiles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    owner_user_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_evaluation_profiles (tenant_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_rule_results (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_case_id BINARY(16) NOT NULL,
    profile_rule_id BINARY(16) NOT NULL,
    evaluator_command_id BINARY(16) NULL,
    evaluator_execution_id BINARY(16) NULL,
    status ENUM('queued','running','passed','failed','error','cancelled') NOT NULL,
    passed BOOLEAN NULL,
    score DECIMAL(12,6) NULL,
    detail_json JSON NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_case_rule (tenant_id, evaluation_run_case_id, profile_rule_id),
    KEY idx_evaluation_rule_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_case_projection (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    evaluation_run_id BINARY(16) NOT NULL,
    source_case_id BINARY(16) NOT NULL,
    target_command_id BINARY(16) NOT NULL,
    target_execution_id BINARY(16) NULL,
    status ENUM('queued','running','scoring','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
    actual_output_json JSON NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost_micros BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_evaluation_run_case (tenant_id, evaluation_run_id, source_case_id),
    UNIQUE KEY uq_evaluation_case_command (target_command_id),
    KEY idx_evaluation_case_status (tenant_id, evaluation_run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE evaluation_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    dataset_version_id BINARY(16) NOT NULL,
    evaluation_profile_version_id BINARY(16) NOT NULL,
    parameters_json JSON NOT NULL,
    status ENUM('created', 'queued', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'created',
    created_by BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_evaluation_runs (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE idempotency_records (
    tenant_id BINARY(16) NOT NULL,
    operation_key VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    resource_id BINARY(16) NULL,
    response_json JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (tenant_id, operation_key, idempotency_key),
    KEY idx_idempotency_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_discovery_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    server_id BINARY(16) NOT NULL,
    server_version_id BINARY(16) NOT NULL,
    status ENUM('running', 'succeeded', 'failed') NOT NULL,
    discovered_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(512) NULL,
    started_by BINARY(16) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_mcp_discovery_server (tenant_id, server_id, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_server_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    server_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    transport ENUM('streamable_http', 'sse') NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    credential_id BINARY(16) NULL,
    configuration_json JSON NOT NULL,
    configuration_hash CHAR(64) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_mcp_server_version (tenant_id, server_id, version_number),
    UNIQUE KEY uq_mcp_server_version_hash (tenant_id, server_id, configuration_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_servers (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    owner_department_id BINARY(16) NOT NULL,
    current_version_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    last_discovered_at TIMESTAMP(6) NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_mcp_server_name (tenant_id, name),
    KEY idx_mcp_servers_tenant (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_tool_policies (
    tenant_id BINARY(16) NOT NULL,
    tool_id BINARY(16) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    debug_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    timeout_seconds INT UNSIGNED NOT NULL DEFAULT 30,
    side_effect ENUM('unknown', 'none', 'read_only', 'idempotent', 'non_idempotent', 'irreversible') NOT NULL DEFAULT 'unknown',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_by BINARY(16) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, tool_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_tool_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    tool_id BINARY(16) NOT NULL,
    discovery_run_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    input_schema JSON NOT NULL,
    output_schema JSON NULL,
    annotations_json JSON NOT NULL,
    schema_hash CHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_mcp_tool_version (tenant_id, tool_id, version_number),
    UNIQUE KEY uq_mcp_tool_schema_hash (tenant_id, tool_id, schema_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mcp_tools (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    server_id BINARY(16) NOT NULL,
    name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NULL,
    description TEXT NULL,
    current_version_number BIGINT UNSIGNED NOT NULL,
    availability ENUM('available', 'unavailable') NOT NULL DEFAULT 'available',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    last_seen_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_mcp_tool_name (tenant_id, server_id, name),
    KEY idx_mcp_tools_server (tenant_id, server_id, availability)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE memory_connections (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    health_path VARCHAR(512) NOT NULL DEFAULT '/health',
    credential_id BINARY(16) NULL,
    owner_department_id BINARY(16) NOT NULL,
    configuration_json JSON NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_memory_connections_tenant (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE memory_namespaces (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    connection_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    external_namespace VARCHAR(512) NOT NULL,
    access_mode ENUM('read', 'read_write') NOT NULL DEFAULT 'read',
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_memory_namespace_external (tenant_id, connection_id, external_namespace),
    KEY idx_memory_namespaces_department (tenant_id, owner_department_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE model_alias_deployment_history (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    alias_id BINARY(16) NOT NULL,
    previous_deployment_id BINARY(16) NULL,
    deployment_id BINARY(16) NOT NULL,
    changed_by BINARY(16) NOT NULL,
    changed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_model_alias_history (tenant_id, alias_id, changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE model_aliases (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    alias VARCHAR(128) NOT NULL,
    deployment_id BINARY(16) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_model_alias (tenant_id, alias)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE model_deployments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    connection_name VARCHAR(160) NOT NULL,
    provider_type ENUM('openai_compatible', 'custom_http') NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    credential_id BINARY(16) NULL,
    owner_department_id BINARY(16) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    max_input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 1050000,
    max_output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 128000,
    default_parameters JSON NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    revision_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
    supersedes_deployment_id BINARY(16) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_model_deployments_department (tenant_id, owner_department_id, status, updated_at),
    KEY idx_model_deployments_credential (tenant_id, credential_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE model_price_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    deployment_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    currency CHAR(3) NOT NULL,
    input_per_million DECIMAL(20,8) NOT NULL,
    output_per_million DECIMAL(20,8) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_model_price_version (tenant_id, deployment_id, version_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE node_definition_versions (
    id BINARY(16) NOT NULL,
    node_definition_id BINARY(16) NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    protocol_version VARCHAR(32) NOT NULL,
    manifest_json JSON NOT NULL,
    manifest_hash VARCHAR(96) NOT NULL,
    capability ENUM('builtin', 'declarative_http', 'remote_action') NOT NULL,
    execution_style ENUM('action', 'trigger', 'suspend', 'sub_workflow') NOT NULL,
    side_effect_level ENUM('none', 'idempotent', 'reversible', 'irreversible') NOT NULL DEFAULT 'none',
    resume_policy JSON NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_definition_version (node_definition_id, version_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE node_definitions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NULL,
    node_type VARCHAR(128) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    source_type ENUM('platform', 'remote') NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_node_definition (tenant_id, node_type),
    KEY idx_node_definition_lookup (node_type, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE notification_receipts (
    tenant_id BINARY(16) NOT NULL,
    notification_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    read_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, notification_id, user_id),
    KEY idx_notification_inbox (tenant_id, user_id, read_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE notifications (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    source_event_id BINARY(16) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    title_key VARCHAR(160) NOT NULL,
    body_key VARCHAR(160) NOT NULL,
    arguments_json JSON NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BINARY(16) NOT NULL,
    target_path VARCHAR(512) NOT NULL,
    tone ENUM('primary', 'success', 'warning', 'danger') NOT NULL DEFAULT 'primary',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_notification_source (tenant_id, source_event_id, notification_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbox (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(128) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    payload_json JSON NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    published_at TIMESTAMP(6) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    last_error VARCHAR(1024) NULL,
    PRIMARY KEY (id),
    KEY idx_outbox_pending (published_at, available_at, occurred_at),
    KEY idx_outbox_tenant_aggregate (tenant_id, aggregate_type, aggregate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE permissions (
    id BINARY(16) NOT NULL,
    permission_key VARCHAR(96) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_permissions_key (permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE projection_receipts (
    projector_name VARCHAR(128) NOT NULL,
    event_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (projector_name, event_id),
    KEY idx_projection_receipts_tenant (tenant_id, processed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_policies (
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    hard_limit DECIMAL(24,6) NOT NULL,
    period_seconds BIGINT UNSIGNED NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, dimension_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_admin_reservations (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    scope_type VARCHAR(64) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    status ENUM('active','settled','released','expired') NOT NULL DEFAULT 'active',
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    settled_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_quota_reservation_scope (tenant_id, dimension_key, scope_type, scope_id),
    KEY idx_quota_reservation_reaper (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE quota_usage_projection (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dimension_key VARCHAR(64) NOT NULL,
    scope_type VARCHAR(64) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_quota_usage_idempotency (tenant_id, idempotency_key),
    KEY idx_quota_usage_window (tenant_id, dimension_key, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE rag_connections (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    health_path VARCHAR(512) NOT NULL DEFAULT '/health',
    credential_id BINARY(16) NULL,
    owner_department_id BINARY(16) NOT NULL,
    configuration_json JSON NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_rag_connections_tenant (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE rag_resources (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    connection_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    external_resource_id VARCHAR(512) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    sync_status ENUM('unknown', 'syncing', 'synced', 'failed') NOT NULL DEFAULT 'unknown',
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_rag_resource_external (tenant_id, connection_id, external_resource_id),
    KEY idx_rag_resources_department (tenant_id, owner_department_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE refresh_sessions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    token_family_id BINARY(16) NOT NULL,
    jti_hash CHAR(64) NOT NULL,
    token_version BIGINT UNSIGNED NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    rotated_at TIMESTAMP(6) NULL,
    revoked_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_refresh_sessions_jti_hash (jti_hash),
    KEY idx_refresh_sessions_user (tenant_id, user_id, revoked_at),
    KEY idx_refresh_sessions_family (token_family_id, revoked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_request_items (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    request_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    required_by_resource_id BINARY(16) NULL,
    owner_department_id BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_item (request_id, resource_type, resource_id, operation_key),
    KEY idx_resource_grant_request_item_department (tenant_id, owner_department_id, request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_request_reviews (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    request_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
    reviewed_by BINARY(16) NULL,
    review_comment VARCHAR(1000) NULL,
    reviewed_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_review (request_id, owner_department_id),
    KEY idx_resource_grant_request_review_inbox (tenant_id, owner_department_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grant_requests (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    workflow_service_identity_id BINARY(16) NOT NULL,
    primary_resource_type VARCHAR(32) NOT NULL,
    primary_resource_id BINARY(16) NOT NULL,
    primary_resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    source_node_id VARCHAR(128) NULL,
    source_revision BIGINT UNSIGNED NULL,
    request_message VARCHAR(1000) NULL,
    dependency_hash VARCHAR(80) NOT NULL,
    open_dedupe_key VARCHAR(80) NULL,
    status ENUM('pending', 'approved', 'rejected', 'cancelled', 'stale') NOT NULL DEFAULT 'pending',
    requested_by BINARY(16) NOT NULL,
    resolved_at TIMESTAMP(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant_request_open (tenant_id, open_dedupe_key),
    KEY idx_resource_grant_request_inbox (tenant_id, status, updated_at),
    KEY idx_resource_grant_request_workflow (tenant_id, workflow_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_grants (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    subject_type ENUM('department', 'workflow_service_identity') NOT NULL,
    subject_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key ENUM('view', 'use', 'read', 'write', 'manage') NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_grant (tenant_id, subject_type, subject_id, resource_type, resource_id, operation_key),
    KEY idx_resource_grant_resource (tenant_id, resource_type, resource_id),
    KEY idx_resource_grant_subject (tenant_id, subject_type, subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE resource_health_checks (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    check_sequence BIGINT UNSIGNED NOT NULL,
    status ENUM('healthy', 'unhealthy', 'unsupported') NOT NULL,
    latency_ms BIGINT UNSIGNED NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(512) NULL,
    checked_by BINARY(16) NOT NULL,
    checked_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_resource_health_sequence (tenant_id, resource_type, resource_id, check_sequence),
    KEY idx_resource_health_latest (tenant_id, resource_type, resource_id, checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_items (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    retention_run_id BINARY(16) NOT NULL,
    data_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    status ENUM('candidate','blocked','deleted','failed') NOT NULL,
    reason VARCHAR(255) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_retention_item_target (retention_run_id, data_type, target_id),
    KEY idx_retention_item_status (tenant_id, retention_run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_policies (
    tenant_id BINARY(16) NOT NULL,
    data_type VARCHAR(64) NOT NULL,
    retention_days INT UNSIGNED NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_by BINARY(16) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, data_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE retention_runs (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    dry_run BOOLEAN NOT NULL,
    status ENUM('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
    requested_by BINARY(16) NOT NULL,
    candidate_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    deleted_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    locked_by BINARY(16) NULL,
    locked_until TIMESTAMP(6) NULL,
    started_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_retention_run_status (status, available_at, locked_until, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE role_permissions (
    tenant_id BINARY(16) NOT NULL,
    role_id BINARY(16) NOT NULL,
    permission_id BINARY(16) NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    KEY idx_role_permissions_tenant (tenant_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE roles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL,
    data_scope ENUM('company', 'department_tree', 'own') NOT NULL,
    is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_roles_tenant_code (tenant_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_profile_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    profile_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    runner ENUM('python', 'javascript', 'shell', 'browser') NOT NULL,
    image_digest VARCHAR(255) NOT NULL,
    cpu_millis INT UNSIGNED NOT NULL,
    memory_bytes BIGINT UNSIGNED NOT NULL,
    pids_limit INT UNSIGNED NOT NULL,
    disk_bytes BIGINT UNSIGNED NOT NULL,
    timeout_seconds INT UNSIGNED NOT NULL,
    output_limit_bytes BIGINT UNSIGNED NOT NULL,
    network_policy_json JSON NOT NULL,
    configuration_hash CHAR(64) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_sandbox_profile_version (tenant_id, profile_id, version_number),
    UNIQUE KEY uq_sandbox_profile_hash (tenant_id, profile_id, configuration_hash),
    CONSTRAINT chk_sandbox_image_digest CHECK (image_digest REGEXP '@sha256:[0-9a-f]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE sandbox_profiles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    current_version_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
    owner_department_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_sandbox_profile_name (tenant_id, name),
    KEY idx_sandbox_profile_status (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_dependencies (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_version_id BINARY(16) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL DEFAULT 'use',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_dependency (skill_version_id, resource_type, resource_id, operation_key),
    KEY idx_skill_dependency_resource (tenant_id, resource_type, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_file_references (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_version_id BINARY(16) NOT NULL,
    source_path VARCHAR(2048) NOT NULL,
    target_path VARCHAR(2048) NOT NULL,
    target_path_hash CHAR(64) NOT NULL,
    target_content_hash CHAR(64) NOT NULL,
    reference_type ENUM('link', 'image') NOT NULL,
    PRIMARY KEY (id),
    KEY idx_skill_reference_target (tenant_id, skill_version_id, target_path_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_file_revisions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_id BINARY(16) NOT NULL,
    entry_id BINARY(16) NOT NULL,
    workspace_revision BIGINT UNSIGNED NOT NULL,
    artifact_id BINARY(16) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_file_revision (tenant_id, skill_id, entry_id, workspace_revision)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_version_files (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_version_id BINARY(16) NOT NULL,
    path VARCHAR(2048) NOT NULL,
    path_hash CHAR(64) NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    artifact_id BINARY(16) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_version_file (tenant_id, skill_version_id, path_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    source_revision BIGINT UNSIGNED NOT NULL,
    manifest_json JSON NOT NULL,
    content_hash VARCHAR(80) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_version (tenant_id, skill_id, version_number),
    UNIQUE KEY uq_skill_version_hash (tenant_id, skill_id, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skill_workspace_entries (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    skill_id BINARY(16) NOT NULL,
    parent_id BINARY(16) NULL,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(2048) NOT NULL,
    path_hash CHAR(64) NOT NULL,
    entry_type ENUM('directory', 'file') NOT NULL,
    mime_type VARCHAR(255) NULL,
    artifact_id BINARY(16) NULL,
    content_hash CHAR(64) NULL,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    editable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_workspace_path (tenant_id, skill_id, path_hash),
    KEY idx_skill_workspace_parent (tenant_id, skill_id, parent_id, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE skills (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    owner_department_id BINARY(16) NOT NULL,
    status ENUM('draft', 'active', 'disabled') NOT NULL DEFAULT 'draft',
    draft_revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_skill_name (tenant_id, name),
    KEY idx_skills_tenant_status (tenant_id, status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tenant_settings (
    tenant_id BINARY(16) NOT NULL,
    locale VARCHAR(16) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tenants (
    id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE trace_delivery_status (
    event_id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    execution_id BINARY(16) NOT NULL,
    payload_json JSON NOT NULL,
    status ENUM('pending', 'streamed', 'delivered') NOT NULL DEFAULT 'pending',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    available_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    streamed_at TIMESTAMP(6) NULL,
    delivered_at TIMESTAMP(6) NULL,
    last_error VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (event_id),
    KEY idx_trace_delivery_pending (status, available_at, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_credentials (
    user_id BINARY(16) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    password_changed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_departments (
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    department_id BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (user_id),
    KEY idx_user_departments_department (tenant_id, department_id, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_roles (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    role_id BINARY(16) NOT NULL,
    scope_department_id BINARY(16) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_user_roles_user (tenant_id, user_id),
    KEY idx_user_roles_role (tenant_id, role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE users (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    username_normalized VARCHAR(64) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    password_change_required BOOLEAN NOT NULL DEFAULT FALSE,
    token_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_tenant_username (tenant_id, username_normalized),
    KEY idx_users_tenant_status (tenant_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_debug_overlays (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    kind ENUM('pin_data', 'mock_output', 'temporary_input', 'history_output', 'artifact') NOT NULL,
    payload_json JSON NOT NULL,
    artifact_id BINARY(16) NULL,
    schema_hash VARCHAR(96) NULL,
    stale BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_debug_overlay_node (tenant_id, workflow_id, node_id),
    KEY idx_workflow_debug_overlay_workflow (tenant_id, workflow_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_deployment_heads (
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    active_deployment_id BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (tenant_id, workflow_id, environment_id),
    UNIQUE KEY uq_workflow_active_deployment (active_deployment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_deployments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    environment_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    sequence_number BIGINT UNSIGNED NOT NULL,
    status ENUM('active', 'superseded', 'rolled_back') NOT NULL DEFAULT 'active',
    source ENUM('publish', 'rollback') NOT NULL DEFAULT 'publish',
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_deployment_sequence (tenant_id, workflow_id, environment_id, sequence_number),
    KEY idx_workflow_deployment_history (tenant_id, workflow_id, environment_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_draft_resources (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    draft_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    node_name VARCHAR(160) NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    relation VARCHAR(64) NOT NULL DEFAULT 'resource_reference',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_draft_resource (
        draft_id, node_id, resource_type, resource_id, operation_key, relation
    ),
    KEY idx_workflow_draft_resources_target (
        tenant_id, resource_type, resource_id, workflow_id
    ),
    KEY idx_workflow_draft_resources_workflow (tenant_id, workflow_id, node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_draft_revisions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    draft_id BINARY(16) NOT NULL,
    revision BIGINT UNSIGNED NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    definition_json JSON NOT NULL,
    content_hash VARCHAR(80) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_draft_revision (tenant_id, workflow_id, revision),
    KEY idx_workflow_revisions_time (tenant_id, workflow_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_drafts (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    definition_json JSON NOT NULL,
    content_hash VARCHAR(80) NOT NULL,
    updated_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_draft (tenant_id, workflow_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_environments (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_environment_code (tenant_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_members (
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    member_role ENUM('viewer', 'editor', 'manager') NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (workflow_id, user_id),
    KEY idx_workflow_members_user (tenant_id, user_id, workflow_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_service_identities (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_service_identity (tenant_id, workflow_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_version_resources (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_version_id BINARY(16) NOT NULL,
    node_id VARCHAR(128) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BINARY(16) NOT NULL,
    resource_version_id BINARY(16) NULL,
    operation_key VARCHAR(32) NOT NULL,
    snapshot_json JSON NOT NULL,
    snapshot_hash VARCHAR(80) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_version_resource (workflow_version_id, node_id, resource_type, resource_id, operation_key),
    KEY idx_workflow_version_resources_lookup (tenant_id, resource_type, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflow_versions (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    workflow_id BINARY(16) NOT NULL,
    version_number BIGINT UNSIGNED NOT NULL,
    source_revision BIGINT UNSIGNED NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    definition_json JSON NOT NULL,
    content_hash VARCHAR(80) NOT NULL,
    created_by BINARY(16) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_workflow_version_number (tenant_id, workflow_id, version_number),
    UNIQUE KEY uq_workflow_version_content (tenant_id, workflow_id, source_revision, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE workflows (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    status ENUM('active', 'archived') NOT NULL DEFAULT 'active',
    visibility ENUM('private', 'department', 'company') NOT NULL DEFAULT 'private',
    owner_user_id BINARY(16) NOT NULL,
    owner_department_id BINARY(16) NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    archived_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    KEY idx_workflows_tenant_status (tenant_id, status, updated_at),
    KEY idx_workflows_department (tenant_id, owner_department_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
-- Representative same-plane tenant constraints. Cross-plane IDs intentionally
-- remain logical references, but core Control identities cannot escape their
-- owning tenant.
ALTER TABLE users
    ADD UNIQUE KEY uq_users_tenant_id (tenant_id, id),
    ADD CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE workflows
    ADD CONSTRAINT fk_workflows_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    ADD CONSTRAINT fk_workflows_owner_user FOREIGN KEY (tenant_id, owner_user_id) REFERENCES users(tenant_id, id);
