apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflow-runtime
  namespace: {{ .Values.global.namespaces.runtime }}
automountServiceAccountToken: false
{{- with .Values.global.images.pullSecretName }}
imagePullSecrets: [{ name: {{ . }} }]
{{- end }}
