apiVersion: v1
kind: ServiceAccount
metadata: { name: agentx-egress-gateway, namespace: {{ .Values.global.namespaces.dependencies }} }
automountServiceAccountToken: false
{{- with .Values.global.images.pullSecretName }}
imagePullSecrets: [{ name: {{ . }} }]
{{- end }}
